#include "zscript/items/doom.zsc"
#include "zscript/items/heretic.zsc"

class BlueBastardHealthBonus : HealthBonus
{
	override bool TryPickup (in out Actor other)
	{
		PrevHealth = other.player != NULL ? other.player.health : other.health;
		
		int blehhh = 200;
		if (other.FindInventory("SpotMallet"))
		{
			blehhh += 50;
		}
		if (other.GiveBody(Amount, blehhh))
		{
			GoAwayAndDie();
			return true;
		}
		return false;
	}
}

class HalfPigInABlanket : BlueBastardHealthBonus
{
	Default
	{
		Inventory.PickupSound "misc/eat";
		Inventory.PickupMessage "$GOTLASTBLANKET";
	}
	States
	{
	Spawn:
		PBNK A -1;
		Loop;
	}
}

class HalfBurger : BlueBastardHealthBonus
{
	Default
	{
		Inventory.PickupSound "misc/eat";
		Inventory.PickupMessage "$GOTHALFBURGER";
	}
	States
	{
	Spawn:
		BURG A -1;
		Loop;
	}
}

class MreBiscuit : BlueBastardHealthBonus
{
	Default
	{
		Inventory.PickupSound "misc/eat";
		Inventory.PickupMessage "$GOTLASTMREBISCUIT";
	}
	States
	{
	Spawn:
		BSCT A -1;
		Loop;
	}
}

class ChipCrumb : BlueBastardHealthBonus
{
	Default
	{
		Inventory.PickupSound "misc/eat";
		Inventory.PickupMessage "$GOTCRUMBS";
	}
	States
	{
	Spawn:
		CHIP A -1;
		Loop;
	}
}

class DrGibbCan : BlueBastardHealthBonus
{
	Default
	{
		Inventory.PickupSound "misc/can_open";
		Inventory.PickupMessage "$GOTDRGIBB";
	}
	States
	{
	Spawn:
		GIBB A -1;
		Loop;
	}
}

class DrGibbGlass : BlueBastardHealthBonus
{
	Default
	{
		Inventory.PickupSound "misc/drink";
		Inventory.PickupMessage "$GOTGLASSDRGIBB";
	}
	States
	{
	Spawn:
		GIBB C -1;
		Loop;
	}
}

class WhiskeyGlass : BlueBastardHealthBonus
{
	Default
	{
		Inventory.PickupSound "misc/drink";
		Inventory.PickupMessage "$GOTGLASSWHISKEY";
	}
	States
	{
	Spawn:
		GIBB D -1;
		Loop;
	}
}

class WhiskeyBottle : Stimpack
{
	Default
	{
		Inventory.PickupSound "misc/bottle_open";
		Inventory.PickupMessage "$GOTWHISKEY";
	}
	States
	{
	Spawn:
		GIBB B -1;
		Loop;
	}
}

class VodkaBottle : Stimpack
{
	Default
	{
		Inventory.PickupSound "misc/bottle_open";
		Inventory.PickupMessage "$GOTVODKA";
	}
	States
	{
	Spawn:
		IVDK A -1;
		Loop;
	}
}

class MysteryCan : Stimpack
{
	Default
	{
		Inventory.PickupSound "misc/can_open";
		Inventory.PickupMessage "$GOTMCAN";
	}
	States
	{
	Spawn:
		MCAN A -1;
		Loop;
	}
}

class ChickenHeal : Medikit
{
	Default
	{
		Inventory.PickupSound "misc/gulp";
		Inventory.PickupMessage "$GOTCHICKEN";
	}
	States
	{
	Spawn:
		CHIK ABCDEF 3;
		Loop;
	}
}

class Medkit_Mslug : Medikit
{
	States
	{
	Spawn:
		MDKT A -1;
		Loop;
	}
}