class DrGibbCan : HealthBonus replaces HealthBonus
{
	Default
	{
		Inventory.PickupSound "misc/can_open";
		Inventory.PickupMessage "$GOTDRGIBB";
	}
	States
	{
	Spawn:
		GIBB A -1;
		Loop;
	}
}

class WhiskeyBottle : Stimpack replaces Stimpack
{
	Default
	{
		Inventory.PickupSound "misc/bottle_open";
		Inventory.PickupMessage "$GOTWHISKEY";
	}
	States
	{
	Spawn:
		GIBB B -1;
		Loop;
	}
}

class BlueBastardBerserk : Berserk replaces Berserk
{
	Default
	{
		Inventory.PickupSound "misc/berserk";
	}
	States
	{
	Pickup:
		TNT1 A 0 A_GiveInventory("PowerStrength");
		TNT1 A 0 HealThing(100, 0);
		TNT1 A 0 A_JumpIfInventory("SpotMallet", 1, 2);
		TNT1 A 0 A_JumpIfInventory("DeathsheadFist", 1, 2);
		Stop;
		TNT1 A 0 A_SelectWeapon("SpotMallet");
		Stop;
		TNT1 A 0 A_SelectWeapon("DeathsheadFist");
		Stop;
	}
}
