// so it doesn't draw the weapons (bueghhhh graphics missing)
class BlueBastardsAltHud : AltHud
{
	override void DrawOneWeapon(PlayerInfo CPlayer, int x, in out int y, Weapon weapon)
	{
	}
	override void DrawWeapons(PlayerInfo CPlayer, int x, int y)
	{
	}
}

class BlueBastardsStatusBar : DoomStatusBar
{
	DynamicValueInterpolator mHealthInterpolator;
	DynamicValueInterpolator mArmorInterpolator;
	int hudwidth, hudheight;
	
	override void Init()
	{
		Super.Init();
		mHealthInterpolator = DynamicValueInterpolator.Create(0, 0.5, 1, 16);
		mArmorInterpolator = DynamicValueInterpolator.Create(0, 0.5, 1, 24);
	}
	override void NewGame ()
	{
		Super.NewGame();
		mHealthInterpolator.Reset (0);
		mArmorInterpolator.Reset (0);
	}
	override void Tick()
	{
		Super.Tick();
		mHealthInterpolator.Update(CPlayer.health);
		let armor = CPlayer.mo.FindInventory("BasicArmor", true);
		if (armor != null) mArmorInterpolator.Update(armor.Amount);
	}
	
	override void Draw (int state, double TicFrac)
	{
		if (state == HUD_StatusBar)
		{
			BeginStatusBar();
			DrawMainBar (TicFrac);
		}
		else if (state == HUD_Fullscreen)
		{
			BeginHUD();
			DrawFullScreenBullshit ();
		}
	}
	
	protected void DrawFullScreenBullshit ()
	{
		Vector2 iconbox = (40, 20);
		DrawImage("graphics/hud_mugshot.png", (4,-36), DI_SCREEN_LEFT_BOTTOM|DI_ITEM_OFFSETS);
		DrawTexture(GetMugShot(5,Mugshot.XDEATHFACE), (5, -35), DI_SCREEN_LEFT_BOTTOM|DI_ITEM_OFFSETS);
		DrawImage("graphics/hud_healthnarmor.png", (44,-49), DI_SCREEN_LEFT_BOTTOM|DI_ITEM_OFFSETS);
		DrawString(mHUDFont, FormatNumber(mHealthInterpolator.GetValue(), 3, 3, FNF_FILLZEROS), (48, -41));
		DrawString(mHUDFont, FormatNumber(mArmorInterpolator.GetValue(), 3, 3, FNF_FILLZEROS), (48, -20));
		
		DrawImage("graphics/hud_ammo.png", (-95,-35), DI_SCREEN_RIGHT_BOTTOM|DI_ITEM_OFFSETS);
		Inventory ammotype1, ammotype2;
		[ammotype1, ammotype2] = GetCurrentAmmo();
		int invY = -20;
		if (ammotype1 != null)
		{
			DrawInventoryIcon(ammotype1, (-20, -4), 0, 1.0, (15,15));
			DrawString(mHUDFont, FormatNumber(ammotype1.Amount, 3, 3, FNF_FILLZEROS), (-32, invY), DI_TEXT_ALIGN_RIGHT);
			invY -= 14;
		}
		if (ammotype2 != null && ammotype2 != ammotype1)
		{
			DrawInventoryIcon(ammotype2, (-20, -19), 0, 1.0, (15,15));
			DrawString(mHUDFont, FormatNumber(ammotype2.Amount, 3, 3, FNF_FILLZEROS), (-32, invY), DI_TEXT_ALIGN_RIGHT);
			invY -= 14;
		}
		if (!isInventoryBarVisible() && !Level.NoInventoryBar && CPlayer.mo.InvSel != null)
		{
			DrawInventoryIcon(CPlayer.mo.InvSel, (-14, invY + 17), DI_DIMDEPLETED);
			DrawString(mHUDFont, FormatNumber(CPlayer.mo.InvSel.Amount, 3), (-30, invY), DI_TEXT_ALIGN_RIGHT);
		}
		if (deathmatch)
		{
			DrawString(mHUDFont, FormatNumber(CPlayer.FragCount, 3), (-3, 1), DI_TEXT_ALIGN_RIGHT, Font.CR_GOLD);
		}
		else
		{
			DrawFullscreenKeys();
		}

		if (isInventoryBarVisible())
		{
			DrawInventoryBar(diparms, (0, 0), 7, DI_SCREEN_CENTER_BOTTOM, HX_SHADOW);
		}
	}

	override void DrawFullscreenKeys()
	{
		bool locks[6];
		String image;
		for(int i = 0; i < 6; i++) locks[i] = CPlayer.mo.CheckKeys(i + 1, false, true);
		// key 1
		if (locks[1] && locks[4]) image = "STKEYS6";
		else if (locks[1]) image = "STKEYS0";
		else if (locks[4]) image = "STKEYS3";
		DrawImage(image, (92, -28), DI_SCREEN_LEFT_BOTTOM|DI_ITEM_OFFSETS);
		// key 2
		if (locks[2] && locks[5]) image = "STKEYS7";
		else if (locks[2]) image = "STKEYS1";
		else if (locks[5]) image = "STKEYS4";
		else image = "";
		DrawImage(image, (92, -20), DI_SCREEN_LEFT_BOTTOM|DI_ITEM_OFFSETS);
		// key 3
		if (locks[0] && locks[3]) image = "STKEYS8";
		else if (locks[0]) image = "STKEYS2";
		else if (locks[3]) image = "STKEYS5";
		else image = "";
		DrawImage(image, (92, -12), DI_SCREEN_LEFT_BOTTOM|DI_ITEM_OFFSETS);
	}
}