#include "zscript/weapons/deathshead.zsc"
#include "zscript/weapons/spot.zsc"
#include "zscript/weapons/doom.zsc"
#include "zscript/weapons/heretic.zsc"

class BlueBastardBulletPuff : BulletPuff
{
	Default
	{
		VSpeed 0;
		RenderStyle "Add";
		Alpha 0.8;
		+NOBLOCKMAP;
		+NOGRAVITY;
		+NOINTERACTION;
		+FORCEXYBILLBOARD;
		Scale 0.5;
	}
	States
	{
	Crash:
		TNT1 A 0 
		{
			scale = default.scale*random(1.0,1.5);
			A_StartSound("misc/ricochet",CHAN_AUTO,CHANF_DEFAULT,random(0,1)*frandom(0.5,1.0));
		}
		TNT1 A 0 A_Jump(192,"Puff1","Puff2");
		Stop;
	Puff1:
		FX57 ABCDEFGHIJ 2 Bright;
		Stop;
	Puff2:
		FX58 ABCDEFGHIJ 2 Bright;
		Stop;
	}
}

class BlueBastardBulletPuffSaw : BlueBastardBulletPuff
{
	Default
	{
		+EXTREMEDEATH
	}
}


class BlueBastardBulletPuffStab : BlueBastardBulletPuff
{
	States
	{
	Crash:
		TNT1 A 0 
		{
			scale = default.scale*random(1.0,1.5);
			A_StartSound("weapons/claw/hitwall",CHAN_AUTO,CHANF_DEFAULT,0.8);
		}
		TNT1 A 0 A_Jump(256,"Puff1","Puff2");
		Stop;
	}
}