class DeathsheadFist : Fist
{
	States
	{
	Ready:
		ADFS A 1 A_WeaponReady;
		Loop;
	Deselect:
		ADFS A 1 A_Lower(24);
		Loop;
	Select:
		ADFS A 1 A_Raise(24);
		Loop;
	Fire:
		ADFS C 2;
		ADFS D 2 A_Punch;
		ADFS D 2 A_WeaponOffset(2.0, 2.0, WOF_ADD);
		ADFS C 2 A_WeaponOffset(0.0, 32.0);
		ADFS CC 2 A_WeaponOffset(2.0, 4.0, WOF_ADD);
		ADFS B 2 A_WeaponOffset(0.0, 32.0);
		ADFS B 2 A_WeaponOffset(2.0, 4.0, WOF_ADD);
		ADFS B 2 A_ReFire;
		Goto Ready;
	}
}