class SpotMallet : Fist
{
	Default
	{
		+WEAPON.NOALERT
	}
	States
	{
	Ready:
		MALL A 1 A_WeaponReady;
		Loop;
	Deselect:
		MALL A 1 A_Lower;
		Loop;
	Select:
		MALL A 1 A_Raise;
		Loop;
	Fire:
		MALL BC 2 A_SetAngle(self.angle + 4);
		MALL C 2;
		Goto Hold_Check;
	Hold_Check:
		MALL C 0{
			if (player.cmd.buttons & BT_ATTACK)
			{
				return ResolveState("Hold");
			} 
			else
			{
				return ResolveState("Swing");
			}
		}
	Hold:
		MALL C 1;
		Goto Hold_Check;
	Swing:
		MALL DEF 1 A_SetAngle(self.angle - 4);
		MALL G 0 A_Recoil(-4);
		MALL G 0;
		MALL G 1{
			int dmg = random(15,50);
			A_SetAngle(self.angle - 4);
			if (FindInventory("PowerStrength"))
			{
				dmg *= 10;
			}
			A_CustomPunch(dmg, norandom:true, range: meleeRange + 20, meleesound: "weapons/mallet", misssound: "weapons/mallet/miss");
		}
		MALL HIJ 1 A_SetAngle(self.angle - 4);
		TNT1 A 10;
		MTCD DCBA 2;
		Goto Ready;
	}
}

class DeathsheadFist : Fist
{
	States
	{
	Ready:
		ADFS A 1 A_WeaponReady;
		Loop;
	Deselect:
		ADFS A 1 A_Lower(24);
		Loop;
	Select:
		ADFS A 1 A_Raise(24);
		Loop;
	Fire:
		ADFS C 2;
		ADFS D 2 A_Punch;
		ADFS D 2 A_WeaponOffset(2.0, 2.0, WOF_ADD);
		ADFS C 2 A_WeaponOffset(0.0, 32.0);
		ADFS CC 2 A_WeaponOffset(2.0, 4.0, WOF_ADD);
		ADFS B 2 A_WeaponOffset(0.0, 32.0);
		ADFS B 2 A_WeaponOffset(2.0, 4.0, WOF_ADD);
		ADFS B 2 A_ReFire;
		Goto Ready;
	}
}

class DeathsheadPistol : Pistol
{
	States
	{
	Ready:
		ADPS A 1 A_WeaponReady;
		Loop;
	Deselect:
		ADPS A 1 A_Lower(20);
		Loop;
	Select:
		ADPS A 1 A_Raise(20);
		Loop;
	Fire:
		ADPS A 2
		{
			A_FireBullets (6, 2, 1, 6, "BulletPuff");
			A_StartSound("weapons/adpistol", CHAN_WEAPON);
		}
		ADPS BB 1 A_WeaponOffset(2.0, 2.0, WOF_ADD);
		ADPS CC 1 A_WeaponOffset(1.0, 3.0, WOF_ADD);
		ADPS D 2 A_WeaponOffset(0.0, 32.0);
		ADPS D 0 A_ReFire;
		Goto Ready;
 	Spawn:
		ADPS A -1;
		Stop;
	}
}