class Spot : DoomPlayer replaces DoomPlayer
{
	Default
	{
		Player.DisplayName "Spot";
		Player.SoundClass "spot";
		Player.Face "SPT";
		Player.ColorRange 192, 207;
		Player.Colorset 0, "$TXT_COLOR_BLUE", 0xC2, 0xCB,  0xCF;
		Player.StartItem "Pistol";
		Player.StartItem "SpotMallet";
		Player.StartItem "Clip", 50;
		Player.WeaponSlot 1, "SpotMallet", "Chainsaw";
	}
	States
	{
	Spawn:
		SPOT A -1;
		Loop;
	See:
		SPOT ABCD 4;
		Loop;
	Missile:
		SPOT E 12;
		Goto Spawn;
	Melee:
		SPOT F 6 BRIGHT;
		Goto Missile;
	Pain:
		SPOT G 4;
		SPOT G 4 A_Pain;
		Goto Spawn;
	Death:
		SPOT H 0 A_PlayerSkinCheck("AltSkinDeath");
	Death1:
		SPOT H 10;
		SPOT I 10 A_PlayerScream;
		SPOT J 10 A_NoBlocking;
		SPOT KLM 10;
		SPOT N -1;
		Stop;
	XDeath:
		SPOT O 0 A_PlayerSkinCheck("AltSkinXDeath");
	XDeath1:
		SPOT O 5;
		SPOT P 5 A_XScream;
		SPOT Q 5 A_NoBlocking;
		SPOT RSTUV 5;
		SPOT W -1;
		Stop;
	AltSkinDeath:
		SPOT H 6;
		SPOT I 6 A_PlayerScream;
		SPOT JK 6;
		SPOT L 6 A_NoBlocking;
		SPOT MNO 6;
		SPOT P -1;
		Stop;
	AltSkinXDeath:
		SPOT Q 5 A_PlayerScream;
		SPOT R 0 A_NoBlocking;
		SPOT R 5 A_SkullPop;
		SPOT STUVWX 5;
		SPOT Y -1;
		Stop;
	}
}

class Deathshead : DoomPlayer replaces DoomPlayer
{
	Default
	{
		Player.DisplayName "Deathshead";
		Player.SoundClass "deathshead";
		Player.Face "MOF";
		Player.DamageScreenColor "37732b";
		Player.ColorRange 192, 207;
		Player.Colorset 0, "$TXT_COLOR_BLUE", 0xC2, 0xCB,  0xCF;
		BloodColor "37732b";
	}
	States
	{
	Spawn:
		MOFF A -1;
		Loop;
	See:
		MOFF ABCD 4;
		Loop;
	Missile:
		MOFF E 12;
		Goto Spawn;
	Melee:
		MOFF F 6 BRIGHT;
		Goto Missile;
	Pain:
		MOFF G 4;
		MOFF G 4 A_Pain;
		Goto Spawn;
	Death:
		MOFF H 0 A_PlayerSkinCheck("AltSkinDeath");
	Death1:
		MOFF H 10;
		MOFF I 10 A_PlayerScream;
		MOFF J 10 A_NoBlocking;
		MOFF KLM 10;
		MOFF N -1;
		Stop;
	XDeath:
		MOFF O 0 A_PlayerSkinCheck("AltSkinXDeath");
	XDeath1:
		MOFF O 5;
		MOFF P 5 A_XScream;
		MOFF Q 5 A_NoBlocking;
		MOFF RSTUV 5;
		MOFF W -1;
		Stop;
	AltSkinDeath:
		MOFF H 6;
		MOFF I 6 A_PlayerScream;
		MOFF JK 6;
		MOFF L 6 A_NoBlocking;
		MOFF MNO 6;
		MOFF P -1;
		Stop;
	AltSkinXDeath:
		MOFF Q 5 A_PlayerScream;
		MOFF R 0 A_NoBlocking;
		MOFF R 5 A_SkullPop;
		MOFF STUVWX 5;
		MOFF Y -1;
		Stop;
	}
}

class SpotMallet : Fist
{
	States
	{
	Ready:
		MALL A 1 A_WeaponReady;
		Loop;
	Deselect:
		MALL A 1 A_Lower;
		Loop;
	Select:
		MALL A 1 A_Raise;
		Loop;
	Fire:
		MALL BC 2 A_SetAngle(self.angle + 4);
		MALL C 2;
		Goto Hold_Check;
	Hold_Check:
		MALL C 0{
			if (player.cmd.buttons & BT_ATTACK)
			{
				return ResolveState("Hold");
			} 
			else
			{
				return ResolveState("Swing");
			}
		}
	Hold:
		MALL C 1;
		Goto Hold_Check;
	Swing:
		MALL DEF 1 A_SetAngle(self.angle - 4);
		MALL G 0 A_Recoil(-4);
		MALL G 0;
		MALL G 1{
			int dmg = 2 * random(1,10);
			A_SetAngle(self.angle - 4);
			if (FindInventory("PowerStrength"))
			{
				dmg *= 10;
			}
			A_CustomPunch(dmg, norandom:true, range: meleeRange + 20, meleesound: "weapons/mallet", misssound: "weapons/mallet/miss");
		}
		MALL HIJ 1 A_SetAngle(self.angle - 4);
		MTCD DCBA 2;
		Goto Ready;
	}
}