class MoffPlayer : DoomPlayer
{
	Default
	{
		Player.DisplayName "Ace Deathshead";
		Player.ColorRange 192, 207;
		Player.Face "MOF";
		Player.DamageScreenColor "37732b";
		Player.SoundClass "moff";
	}
	States
	{
	Spawn:
		MOFF A -1;
		Loop;
	See:
		MOFF ABCD 4;
		Loop;
	Missile:
		MOFF E 12;
		Goto Spawn;
	Melee:
		MOFF F 6 BRIGHT;
		Goto Missile;
	Pain:
		MOFF G 4;
		MOFF G 4 A_Pain;
		Goto Spawn;
	Death:
		MOFF H 0 A_PlayerSkinCheck("AltSkinDeath");
	Death1:
		MOFF H 10;
		MOFF I 10 A_PlayerScream;
		MOFF J 10 A_NoBlocking;
		MOFF KLM 10;
		MOFF N -1;
		Stop;
	XDeath:
		MOFF O 0 A_PlayerSkinCheck("AltSkinXDeath");
	XDeath1:
		MOFF O 5;
		MOFF P 5 A_XScream;
		MOFF Q 5 A_NoBlocking;
		MOFF RSTUV 5;
		MOFF W -1;
		Stop;
	AltSkinDeath:
		MOFF H 6;
		MOFF I 6 A_PlayerScream;
		MOFF JK 6;
		MOFF L 6 A_NoBlocking;
		MOFF MNO 6;
		MOFF P -1;
		Stop;
	AltSkinXDeath:
		MOFF Q 5 A_PlayerScream;
		MOFF R 0 A_NoBlocking;
		MOFF R 5 A_SkullPop;
		MOFF STUVWX 5;
		MOFF Y -1;
		Stop;
	}
}
