#library "Transform"
#include "zcommon.acs"

Script "Transform" ENTER
{
	while (True){
		Delay(1);
		if (GetCvar("allow_spot_dragon")){
			if (GetPlayerInput(-1,INPUT_OLDBUTTONS)&BT_RELOAD){
				if (CheckInventory("Dragon_Spot_Transform")){
					UseInventory("Dragon_Spot_Transform");
					Delay(945);
					GiveInventory("Dragon_Spot_Transform_End",1);
					UseInventory("Dragon_Spot_Transform_End");
				}
				if (CheckInventory("Mothman_Transform")){
					UseInventory("Mothman_Transform");
					Delay(945);
					GiveInventory("Mothman_Transform_End",1);
					UseInventory("Mothman_Transform_End");
				}
			}
		}
	}
}