class DeathsheadLevelEnter : BlueBastardWeapon
{
	mixin BBDeathsheadWeapon;
	Default
	{
		Tag " ";
		+INVENTORY.UNDROPPABLE
	}
	States
	{
	Select:
		TNT1 A 0 A_JumpIf(skip_intros == true, "Fire");
		TNT1 A 1 A_Raise(24);
		Wait;
	Deselect:
		TNT1 A 1 A_Lower(24);
		Wait;
	Ready:
		TNT1 A 0 A_Jump(256,"Ready1","Ready2","Ready3","Ready4","Ready5");
	Ready1:
		ADWD A 2 A_StartSound("misc/bottle_open", CHAN_AUTO);
		ADWD BCDEF 2;
		ADWD G 2 A_StartSound("misc/drink", CHAN_AUTO);
		ADWD H 2;
		ADWD F 3;
		ADWD G 2 A_StartSound("misc/drink", CHAN_AUTO);
		ADWD H 2;
		ADWD F 3;
		ADWD G 2 A_StartSound("misc/drink", CHAN_AUTO);
		ADWD H 2;
		ADWD F 3;
		ADWD I 2 A_StartSound("weapons/deagle/deploy", CHAN_AUTO);
		ADWD JKLMNOPQRSTUVW 2;
		TNT1 A 2;
		TNT1 A 2 A_StartSound("misc/glass_break", CHAN_AUTO);
		Goto Fire;
	Ready2:
		ADFK ABCD 2;
		ADFK E 2 A_StartSound("weapons/fists/deploy");
		ADFK FGHIJKL 2;
		Goto Fire;
	Ready3:
		ADDR A 2 A_StartSound("misc/can_open", CHAN_AUTO);
		ADDR BCDEFGH 2;
		ADDR I 2 A_StartSound("misc/drink", CHAN_AUTO);
		ADDR JKLMNOP 2;
		ADDR QR 1;
		ADDR S 1 A_StartSound("misc/throw", CHAN_AUTO);
		ADDR TU 1;
		TNT1 A 4;
		TNT1 A 2 A_StartSound("misc/drop", CHAN_AUTO);
		Goto Fire;
	Ready4:
		ADMA ABCDEFGHIJKLMEDCBA 2;
		Goto Fire;
	Ready5:
		ADSM ABCDE 2;
		ADSM F 2 A_StartSound("misc/zippo/open");
		ADSM GHIJKL 2;
		ADSM M 2 A_StartSound("misc/zippo/close");
		ADSM NOPQRS 2;
		Goto Fire;
	Fire:
		TNT1 A 1 A_TakeInventory("DeathsheadLevelEnter");
		Wait;
	}
}