class HealthBonusSpawner : RandomSpawner replaces HealthBonus
{
    Default
    {
        DropItem "DrGibbCan";
        DropItem "DrGibbGlass";
        DropItem "WhiskeyGlass";
    }
}

class BlueBastardBerserk : Berserk replaces Berserk
{
	Default
	{
		Inventory.PickupSound "misc/berserk";
	}
	States
	{
	Pickup:
		TNT1 A 0 A_GiveInventory("PowerStrength");
		TNT1 A 0 HealThing(100, 0);
		TNT1 A 0 A_JumpIfInventory("SpotMallet", 1, 2);
		TNT1 A 0 A_JumpIfInventory("DeathsheadFist", 1, 2);
		Stop;
		TNT1 A 0 A_SelectWeapon("SpotMallet");
		Stop;
		TNT1 A 0 A_SelectWeapon("DeathsheadFist");
		Stop;
	}
}

class BlueBastardBackpack : Backpack replaces Backpack
{
	Default
	{
		Inventory.PickupMessage "$GOTBACKPACK";
		Inventory.PickupSound "misc/metalslug";
	}
	States
	{
	Spawn:
		BPAK A 16;
		BPAK BCDEF 2;
		Loop;
	}
}