class HealthBonusSpawner : RandomSpawner replaces HealthBonus
{
    Default
    {
        DropItem "DrGibbCan";
        DropItem "DrGibbGlass";
        DropItem "WhiskeyGlass";
		DropItem "HalfPigInABlanket";
		DropItem "HalfBurger";
		DropItem "MreBiscuit";
		DropItem "ChipCrumb";
    }
}

class StimPackSpawner : RandomSpawner replaces StimPack
{
    Default
    {
        DropItem "WhiskeyBottle";
        DropItem "VodkaBottle";
		DropItem "MysteryCan";
    }
}

class MedikitSpawner : RandomSpawner replaces Medikit
{
    Default
    {
        DropItem "ChickenHeal";
        DropItem "Medkit_Mslug";
    }
}

class BlueBastardBackpack : Backpack replaces Backpack
{
	Default
	{
		Inventory.PickupMessage "$GOTBACKPACK";
		Inventory.PickupSound "misc/metalslug";
	}
	States
	{
	Spawn:
		BPAK A 16;
		BPAK BCDEF 2;
		Loop;
	}
}

class SoulsphereReplacement : Soulsphere replaces Soulsphere
{
	override bool TryPickup (in out Actor other)
	{
		PrevHealth = other.player != NULL ? other.player.health : other.health;
		
		int blehhh = 200;
		if (other.FindInventory("SpotMallet"))
		{
			blehhh += 50;
		}
		if (other.GiveBody(Amount, blehhh))
		{
			GoAwayAndDie();
			return true;
		}
		return false;
	}
}
