class HealthBonusSpawner : RandomSpawner replaces HealthBonus
{
    Default
    {
        DropItem "DrGibbCan";
        DropItem "DrGibbGlass";
        DropItem "WhiskeyGlass";
    }
}

class StimPackSpawner : RandomSpawner replaces StimPack
{
    Default
    {
        DropItem "WhiskeyBottle";
        DropItem "VodkaBottle";
		DropItem "MysteryCan";
    }
}

class MedikitSpawner : RandomSpawner replaces Medikit
{
    Default
    {
        DropItem "ChickenHeal";
        DropItem "Medkit_Mslug";
    }
}

class BlueBastardBerserk : Berserk replaces Berserk
{
	Default
	{
		Inventory.PickupSound "misc/berserk";
	}
	States
	{
	Pickup:
		TNT1 A 0 A_GiveInventory("PowerStrength");
		TNT1 A 0 HealThing(100, 0);
		TNT1 A 0 A_JumpIfInventory("SpotMallet", 1, 2);
		TNT1 A 0 A_JumpIfInventory("DeathsheadFist", 1, 2);
		Stop;
		TNT1 A 0 A_SelectWeapon("SpotMallet");
		Stop;
		TNT1 A 0 A_SelectWeapon("DeathsheadFist");
		Stop;
	}
}

class BlueBastardBackpack : Backpack replaces Backpack
{
	Default
	{
		Inventory.PickupMessage "$GOTBACKPACK";
		Inventory.PickupSound "misc/metalslug";
	}
	States
	{
	Spawn:
		BPAK A 16;
		BPAK BCDEF 2;
		Loop;
	}
}

class SoulsphereReplacement : Soulsphere replaces Soulsphere
{
	override bool TryPickup (in out Actor other)
	{
		PrevHealth = other.player != NULL ? other.player.health : other.health;
		
		int blehhh = 200;
		if (other.FindInventory("SpotMallet"))
		{
			blehhh += 50;
		}
		if (other.GiveBody(Amount, blehhh))
		{
			GoAwayAndDie();
			return true;
		}
		return false;
	}
}