
//If I can pose a suggestion, I'd say make two separate kinda of cell ammo, one for the BFG and Plasma Gun/your new gun
//Maybe make the new gun not shoot cells plasma rifle specifically but have it maybe be a low powered energy beam
//For more focused shots whilst the Plasma gun could be used for more rapid firing devastating plasma shots like the original
//ve e vett from discord

class DinkyBlaster : Pistol
{
    Default
    {
        Weapon.AmmoGive 20;
        Weapon.AmmoUse 1;
        Weapon.AmmoType "Cell";
    }

	States
	{
	Ready:
		DNKB A 1 A_WeaponReady;
		Loop;
	Deselect:
		DNKB A 1 A_Lower;
		Loop;
	Select:
		DNKB A 1 A_Raise;
		Loop;
	Fire:
        DNKB A 0 A_GunFlash;
        DNKB A 0 A_PlaySound("weapons/blaster/shoot");
		DNKB C 3 A_FireBullets(1, 0, 0, 5, "DinkyPuff");
        DNKB B 4;
        DNKB A 4;
        DNKB A 0 A_ReFire;
        Goto Ready;
    Flash:
        DKFR A 3 Bright A_Light1;
        TNT1 A 1 A_Light0;
        stop;
    Spawn:
        BLST A -1;
        stop;
	}
}

class DinkyPuff : BulletPuff
{
    Default
    {
        RenderStyle "Add";
        Alpha 0.5;
        Scale 0.5;
        +NOBLOCKMAP;
        +NOGRAVITY;
    }
    States
    {
        Melee:
            Goto Spawn;
        Spawn:
            PLSE ABCDE 2 Bright;
            stop;
    }
}