class Dragon_Spot_Transform : CustomInventory {
    mixin BBSpotWeapon;
    Default
	{
		Tag " ";
		+INVENTORY.UNDROPPABLE
	}

    action void TryTransform()
    {
        A_Print("Attempting To Transform");
        let ppawn = PlayerPawn(self);

        if (!ppawn){
            return;
        }

        if (ppawn.Alternative == null){
            A_PlaySound("misc/berserk");
            A_Morph("SpotDragon", 35 * 30, MRF_FULLHEALTH);
        }
    }

    States {
        Use:
            TNT1 A 0 TryTransform();
            stop;
    }
}


// Gao :3
class BBSpot_Dragon_Claws : BlueBastardWeapon 
{
    Default
	{
		+WEAPON.MELEEWEAPON

        Weapon.BobStyle "InverseSmooth";
		Weapon.BobSpeed 2.5;
		Weapon.BobRangeX 0;
		Weapon.BobRangeY 1;
	}

    States
	{
	Deselect:
		TNT1 A 0 A_Lower(24); 
		Loop;
	Select:
		TNT1 A 0 A_Raise(24);
		Loop;
    Ready:
		PUNG ABCDCB 1 A_WeaponReady;
    RealReady:
        PUNG A 1 A_WeaponReady;
        Loop;
	Fire:
		PUNG B 2;
		PUNG C 2 A_Punch;
		PUNG DCB 2;
		PUNG B 2 A_ReFire;
		Goto RealReady;
    AltFire:
        PUNG C 4 A_FireProjectile("DragonFlame", 0, false);
        Goto RealReady;
	}
}

// Will implement proper projectile soon, but it should be good for now
class DragonFlame : NapalmFlame{
    Default{
        Projectile;
        Speed 16;
    }
}