class Dragon_Spot_Transform : CustomInventory {
    mixin BBSpotWeapon;
    Default
	{
		Tag " ";
		+INVENTORY.UNDROPPABLE
	}

    action void TryTransform()
    {
        A_Print("Attempting To Transform");
        let ppawn = PlayerPawn(self);

        if (!ppawn){
            return;
        }

        if (ppawn.Alternative == null){
            A_PlaySound("misc/berserk");
            A_Morph("SpotDragon", 35 * 30, MRF_FULLHEALTH);
        }
    }

    States {
        Use:
            TNT1 A 0 TryTransform();
            stop;
    }
}


// Gao :3
class BBSpot_Dragon_Claws : BlueBastardWeapon 
{
    mixin BBSpotWeapon;

    int which_claw;

    Default
	{
		+WEAPON.MELEEWEAPON

        Weapon.BobStyle "InverseSmooth";
		Weapon.BobSpeed 2.5;
		Weapon.BobRangeX 0;
		Weapon.BobRangeY 1;
	}

    override void PostBeginPlay(){
        Super.PostBeginPlay();
        which_claw = 0;
    }

    States
	{
	Deselect:
        DCWR ABCDEF 2;
		TNT1 A 0 A_Lower(24); 
		Loop;
	Select:
		TNT1 A 0 A_Raise(24);
		Loop;
    Ready:
		DCWR FEDCBA 2;
    RealReady:
        DGCI ABCB 4 A_WeaponReady;
        Loop;
	Fire:
        TNT1 A 0{

            // Probably possible to do it in a single line, but it works for now.
            invoker.which_claw += 1;
            invoker.which_claw = invoker.which_claw % 2;

            // Check which claw to use, programmed this in so 
            switch(invoker.which_claw)
            {
                case 0:
                    return ResolveState("Claw_Left");
                    break;
                case 1: 
                    return ResolveState("Claw_Right");
                    break;
            }
            return ResolveState(null);
        }
		stop;
    Claw_Left:
        DGCL AB 1;
        DGCL C 1{
			int dmg = random(5,15);
			if (FindInventory("PowerStrength"))
			{
				dmg *= 10;
			}
			A_CustomPunch(dmg, norandom:true, range: meleeRange + 20, meleesound: "imp/melee", misssound: "weapons/mallet/miss");
		}
        DGCL DE 1;
        DCWR FDB 1 A_Refire("Fire");
        Goto RealReady;
    Claw_Right:
        DGCR AB 1;
        DGCR C 1{
			int dmg = random(5,15);
			if (FindInventory("PowerStrength"))
			{
				dmg *= 10;
			}
			A_CustomPunch(dmg, norandom:true, range: meleeRange + 20, meleesound: "imp/melee", misssound: "weapons/mallet/miss");
		}
        DGCR DE 1;
        DCWR FDB 1 A_Refire("Fire");
        Goto RealReady;
    AltFire:
        DGFR ABC 2;
    HoldAlt:
        DGFR C 2{
            A_WeaponOffset(Random(-2,2),Random(-2,2)+36);
            A_FireProjectile("DragonFlame", 0, 0 ,0);
        }
        DGFR BA 2 A_Refire("HoldAlt");
        Goto RealReady;
	}
}

// Will implement proper projectile soon, but it should be good for now
class DragonFlame : NapalmFlame{
    Default{
        Projectile;
        Speed 16;
    }
}