class DeathsheadFist : Fist
{
	Default
	{
		Weapon.BobStyle "Smooth";
		Weapon.BobRangeX 1.5;
		+WEAPON.NOALERT
		+INVENTORY.UNDROPPABLE
		Tag "$ACE_FISTS";
	}
	States
	{
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Deselect:
		ADFS A 1 A_Lower(24);
		Wait;
	Ready:
		ADFS HG 2;
		ADFS E 2 A_StartSound("weapons/fists/deploy");
		ADFS FGHIJA 2;
	RealReady:
		ADFS A 1 A_WeaponReady(WRF_ALLOWRELOAD);
		Wait;
	Deselect:
		ADFS A 1 A_Lower(24);
		Loop;
	Select:
		ADFS A 1 A_Raise(24);
		Loop;
	Fire:
		ADFS BC 1;
		ADFS D 2 
		{
			int dmg = random(8,24);
			if (FindInventory("PowerStrength"))
			{
				dmg *= 10;
			}
			A_CustomPunch(dmg, norandom:true, range: meleeRange + 20, meleesound: "*fist", misssound: "weapons/weakswing");
		}
		ADFS D 2 A_WeaponOffset(2.0, 2.0, WOF_ADD);
		ADFS CBA 3 A_WeaponOffset(0.0, 32.0);
		ADFS A 2 A_ReFire;
		Goto RealReady;
	AltFire:
		ADGB AB 2;
		ADGB C 2 
		{
			int dmg = random(2,48);
			if (FindInventory("PowerStrength"))
			{
				dmg *= 2;
			}
			A_CustomPunch(dmg, norandom:true, pufftype:"BlueBastardBulletPuffStab", range: meleeRange + 20, meleesound: "weapons/claw/impact", misssound: "weapons/weakswing");
		}
		ADGB DE 2;
		ADGB F 2 A_ReFire;
		Goto RealReady;
	Reload:
		ADFS HG 2;
		ADFS E 2 A_StartSound("weapons/fists/deploy");
		ADFS FGHIJ 2;
		Goto RealReady;
	}
}

class DeathsheadChainsaw : Chainsaw
{
	Default
	{
		Weapon.UpSound "";
		Weapon.BobStyle "InverseSmooth";
		Weapon.BobRangeX 0.5;
		Tag "$ACE_CHAINSAW";
		+INVENTORY.UNDROPPABLE
	}
	States
	{
	Select:
		ADCS N 1 A_Raise(24);
		Wait;
	Deselect:
		TNT1 A 0 A_StopSound(6);
		TNT1 A 0 A_StopSound(7);
		TNT1 A 0 A_StartSound("weapons/sawidle", 7, CHANF_DEFAULT, 0.75);
		ADCS KLMN 2;
		TNT1 A 1 A_Lower(24);
		Wait;
	Ready:
		ADCS N 2 A_StartSound("weapons/generic/draw", CHAN_AUTO);
		ADCS OPQRSTU 2;
		ADCS V 2 A_StartSound("weapons/chainsaw/start", CHAN_AUTO);
		ADCS W 2 A_StartSound("weapons/sawup", CHAN_AUTO);
		ADCS XYZ[D 2;
	RealReady:
		TNT1 A 0 A_StopSound(6);
		TNT1 A 0 A_StopSound(7);
		TNT1 A 0 A_StartSound("weapons/sawidle", 7, CHANF_DEFAULT, 0.75);
		ADCS ABCD 2 A_WeaponReady;
		Loop;
	Fire:
		TNT1 A 0 A_StartSound("weapons/sawfull", 6, CHANF_LOOPING, 0.75);
		ADCS E 1;
	Hold:
		ADCS F 0 A_Saw("","weapons/chainsaw",2,"BlueBastardBulletPuffSaw");
		ADCS FG 1
		{
			A_WeaponOffset(random(-2.0,2.0), random(32.0,40.0),WOF_INTERPOLATE);
		}
		ADCS H 0 A_Saw("","weapons/chainsaw",2,"BlueBastardBulletPuffSaw");
		ADCS HI 1
		{
			A_WeaponOffset(random(-2.0,2.0), random(32.0,40.0),WOF_INTERPOLATE);
		}
		ADCS J 1 A_ReFire;
		Goto RealReady;
	}
}

class DeathsheadPistol : Pistol
{
	Default
	{
		Weapon.BobRangeX 0.5;
		Weapon.BobSpeed 1.5;
		Weapon.BobStyle "InverseSmooth";
		+WEAPON.NOAUTOFIRE
		+INVENTORY.UNDROPPABLE
		Tag "$ACE_PISTOL";
	}
	States
	{
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Deselect:
		ADPS FGHIJKL 2;
		TNT1 A 1 A_Lower(24);
		Wait;
	Ready:
		ADPS L 2 A_StartSound("weapons/adpistol/deploy");
		ADPS KJIHGFEA 2;
	RealReady:
		ADPS A 1 A_WeaponReady;
		Wait;
	Fire:
		ADPS B 1 Bright
		{
			A_FireBullets (4, 2, -1, random(8,20), "BlueBastardBulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			A_StartSound("weapons/adpistol", CHAN_AUTO);
			A_GunFlash();
		}
		ADPS B 1 Bright A_WeaponReady(WRF_NOSWITCH);
		ADPS CD 2 Bright A_WeaponReady(WRF_NOSWITCH);
		ADPS EA 2 A_WeaponReady(WRF_NOSWITCH);
		Goto RealReady;
	Flash:
		ADPS M 2 Bright A_Light2;
		ADPS N 2 Bright A_Light1;
		Goto LightDone;
 	Spawn:
		ADPS A -1;
		Stop;
	}
}

class DeathsheadMAC10 : Chaingun
{
	Default
	{
		Weapon.BobRangeX 0.5;
		Weapon.BobSpeed 1.5;
		Weapon.BobStyle "InverseSmooth";
		Tag "$ACE_MAC10";
		+INVENTORY.UNDROPPABLE
	}
	States
	{
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Deselect:
		ADMC DEFGH 2;
		TNT1 A 1 A_Lower(24);
		Wait;
	Ready:
		ADMC H 2 A_StartSound("weapons/generic/draw");
		ADMC IJKL 2;
		ADMC M 2 A_StartSound("weapons/mac10/deploy");
		ADMC NOPQRS 2;
	RealReady:
		ADMC A 1 A_WeaponReady;
		Loop;
	Fire:
		ADMC A 0 A_GunFlash;
		ADMC BC 2 Bright
		{
			A_FireBullets (7, 4, -1, random(4,12), "BlueBastardBulletPuff", FBF_NORANDOM);
			A_FireBullets (7, 4, -1, random(4,12), "BlueBastardBulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			A_StartSound("weapons/mac10", CHAN_AUTO);
			A_WeaponOffset(random(-4.0,8.0), random(32.0,48.0),WOF_INTERPOLATE);
		}
		ADMC A 0 A_ReFire;
		Goto RealReady;
	Flash:
		ADMC T 1 Bright A_Light2;
		ADMC U 1 Bright A_Light1;
		ADMC V 1 Bright A_Light2;
		ADMC W 1 Bright A_Light1;
		Goto LightDone;
	Spawn:
		ADMC A -1;
		Stop;
	}
}

class DeathsheadShotgun : Shotgun
{
	Default
	{
		Weapon.BobRangeY 0.5;
		Weapon.BobStyle "InverseSmooth";
		Tag "$ACE_AUTOSHOTGUN";
		+INVENTORY.UNDROPPABLE
	}
	States
	{
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Deselect:
		ADSG GHIJKLM 2;
		TNT1 A 1 A_Lower(24);
		Wait;
	Ready:
		ADSG M 2 A_StartSound("weapons/autoshotgun/deploy");
		ADSG LKJIHGA 2;
	RealReady:
		ADSG A 1 A_WeaponReady;
		Loop;
	Fire:
		ADSG B 1 Bright
		{
			A_FireBullets (6, 6, 12, random(2,5), "BlueBastardBulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			A_StartSound("weapons/autoshotgun", CHAN_AUTO);
			A_GunFlash();
		}
		ADSG C 2 Bright;
		ADSG D 2 Bright;
		ADSG EFA 2 A_ReFire;
		Goto RealReady;
	Flash:
		ADSG N 1 Bright A_Light2;
		ADSG O 2 Bright A_Light1;
		Goto LightDone;
	}
}

class DeathsheadSuperShotgunActive : Inventory 
{ 
	Default
	{
		Inventory.MaxAmount 1; 
	}
}
class DeathsheadSuperShotgun : SuperShotgun
{
	Default
	{
		Weapon.AmmoUse 4;
		Weapon.AmmoGive 16;
		Weapon.BobSpeed 1.75;
		Weapon.BobStyle "InverseSmooth";
		Tag "$ACE_SAWNOFFS";
		+INVENTORY.UNDROPPABLE;
	}
    States
	{
	Ready:
		ADDB I 0 A_GiveInventory("DeathsheadSuperShotgunActive");
		ADDB I 2 A_StartSound("weapons/sshotc", CHAN_AUTO);
		ADDB HGFE 2;
	RealReady:
		ADDB A 0 A_JumpIf(GetPlayerInput(INPUT_BUTTONS) & BT_ATTACK, "Fire");
		ADDB A 1 A_WeaponReady(WRF_NOPRIMARY);
		Goto RealReady;
	LeftReady:
		ADDB I 0 {
			A_OverlayFlags(OverlayID(),PSPF_MIRROR|PSPF_FLIP,1);
			A_OverlayFlags(OverlayID(),PSPF_ADDWEAPON,0);
			A_OverlayOffset(OverlayID(),0,32);
			A_StartSound("weapons/sshotc", CHAN_AUTO);
		}
		ADDB IHGFE 2;
	LeftRealReady:
		ADDB A 0 A_JumpIf(GetPlayerInput(INPUT_BUTTONS) & BT_ATTACK, "LeftFire");
		ADDB A 1;
		Loop;
	Select:
		ADDB I 0 A_Overlay(2,"LeftSelect");
		ADDB I 1 A_Raise(24);
		Wait;
	LeftSelect:
		TNT1 A 0 A_OverlayFlags(OverlayID(),PSPF_MIRROR|PSPF_FLIP,1);
		ADDB I 1 A_JumpIf(CountInv("DeathsheadSuperShotgunActive"),"LeftReady");
		Wait;
	Deselect:
		ADDB A 0 {
			A_TakeInventory("DeathsheadSuperShotgunActive");
			A_Overlay(2,"LeftDeselect");
		}
		ADDB EFGHI 2;
		ADDB I 1 A_Lower(24);
		Wait;
	LeftDeselect:
		ADDB A 0 A_OverlayFlags(OverlayID(),PSPF_MIRROR|PSPF_FLIP,1);
		ADDB EFGHI 2;
		ADDB I 1;
		Wait;
	Fire:
		ADDB B 2 Bright {
			A_FireBullets(12.8, 8.2, 48, random(3,6), "BlueBastardBulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			A_StartSound("weapons/shotgun/fire", CHAN_AUTO);
			A_StartSound("weapons/doubleshotties", CHAN_AUTO, CHANF_DEFAULT, 0.3);
			A_GunFlash();
		}
		ADDB C 2 Bright;
		ADDB D 2;
		ADDB A 0 A_CheckReload;
		ADDB EFG 2;
		ADDB H 2 A_StartSound("weapons/sshoto", CHAN_AUTO);
		ADDB I 2 A_StartSound("weapons/sshotl", CHAN_AUTO);
		ADDB J 2 A_StartSound("weapons/sshotc", CHAN_AUTO);
		ADDB KLC 2;
		Goto RealReady;
	LeftFire:
		ADDB B 2 Bright A_Overlay(3, "LeftFlash");
		ADDB C 2 Bright;
		ADDB DEFGHIJKLC 2;
		Goto LeftRealReady;
	Flash:
		ADDB M 2 Bright A_Light1;
		ADDB N 2 Bright A_Light2;
		Goto LightDone;
	LeftFlash:
		ADDB M 0 Bright {
			A_OverlayFlags(OverlayID(),PSPF_MIRROR|PSPF_FLIP,1);
			A_OverlayFlags(OverlayID(),PSPF_ADDWEAPON,0);
			A_OverlayOffset(OverlayID(),0,32);
		}
		ADDB M 2 Bright A_Light1;
		ADDB N 2 Bright A_Light2;
		Stop;
	}
}

class DeathsheadRocketLauncher : RocketLauncher
{
	Default
	{
		Weapon.BobRangeX 1.5;
		Weapon.BobRangeY 0.5;
		Weapon.BobStyle "InverseSmooth";
		Tag "$ACE_ROCKET";
		+INVENTORY.UNDROPPABLE
	}
	States
	{
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Deselect:
		ADRK JIHGF 2;
		TNT1 A 1 A_Lower(24);
		Wait;
	Ready:
		ADRK F 2 A_StartSound("weapons/rocket/load");
		ADRK GHIJA 2;
	RealReady:
		ADRK A 1 A_WeaponReady;
		Loop;
	Fire:
		ADRK B 0
		{
			A_StartSound("weapons/rocket", CHAN_AUTO);
			A_FireMissile();
		}
		ADRK BC 2 Bright A_WeaponOffset(8.0, 8.0, WOF_ADD|WOF_INTERPOLATE);
		ADRK DE 2 Bright A_WeaponOffset(2.0, 2.0, WOF_ADD|WOF_INTERPOLATE);
		ADRK A 0 A_StartSound("weapons/rocket/load", CHAN_AUTO, CHANF_DEFAULT, 0.5);
		ADRK AA 2 Bright A_WeaponOffset(-2.0, -2.0, WOF_ADD|WOF_INTERPOLATE);
		ADRK AA 2 Bright A_WeaponOffset(-8.0, -8.0, WOF_ADD|WOF_INTERPOLATE);
		ADRK A 2 A_ReFire;
		Goto RealReady;
	}
}

class DeathsheadPlasmaRifle : PlasmaRifle
{
	Default
	{
		Weapon.BobRangeX 1.25;
		Weapon.BobRangeY 0.75;
		Weapon.BobStyle "InverseSmooth";
		Weapon.WeaponScaleX 0.9;
		Weapon.WeaponScaleY 1.08;
		Weapon.AmmoUse 5;
		Tag "$ACE_PLASMA";
		+INVENTORY.UNDROPPABLE
	}
	States
	{
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Deselect:
		ADPC GHIJKLM 1;
		TNT1 A 1 A_Lower(24);
		Wait;
	Ready:
		ADPC M 1 A_StartSound("weapons/plasmacannon/deploy");
		ADPC LKJIHGA 1;
	RealReady:
		ADPC A 1 A_WeaponReady;
		Loop;
	Fire:
		ADPC B 2 Bright
		{
			A_StartSound("weapons/plasmacannon", CHAN_WEAPON);
			for (int i = 0; i < 5; i++)
			{
				A_FireProjectile("PlasmaCannonBall",random(-3.0,3.0),false,0,0,0,random(-3.0,3.0));
			}
			A_FireProjectile("PlasmaCannonBall",0,true);
			A_GunFlash();
		}
		ADPC C 2 Bright;
		ADPC DAAAAA 2;
		ADPC A 0 A_ReFire;
		Goto RealReady;
	Flash:
		ADPC E 2 Bright A_Light1;
		ADPC F 2 Bright A_Light1;
		Goto LightDone;
	Spawn:
		PLAS A -1;
		Stop;
	}
}

class PlasmaCannonBall : PlasmaBall
{
	Default
	{
		Damage 4;
		Speed 50;
		SeeSound "";
	}
	States
	{
	Death:
		PLSE A 0 Bright A_Explode(random(1,10),96,0);
		PLSE A 4 Bright A_Explode(random(1,5),56,XF_HURTSOURCE);
		PLSE BCDE 4 Bright;
		Stop;
	}
}

class DeathsheadBFG : BFG9000
{
	Default
	{
		Weapon.BobRangeX 1.5;
		Weapon.BobRangeY 0.5;
		Weapon.BobStyle "InverseSmooth";
		Tag "$ACE_BFG";
		+INVENTORY.UNDROPPABLE
	}
	States
	{
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Deselect:
		NBFG AMLKJ 2;
		TNT1 A 1 A_Lower(24);
		Wait;
	Ready:
		NBFG J 2 A_StartSound("weapons/bfgq2/deploy");
		NBFG KLMAA 2;
	RealReady:
		NBFG A 1 A_WeaponReady;
		Loop;
	Fire:
		NBFG A 0 A_StartSound("weapons/bfgq2", CHAN_AUTO); 
		NBFG AAAAAAAAAA 1 Bright A_WeaponOffset(random(-2.0,2.0), random(32.0,34.0),WOF_INTERPOLATE);
		NBFG CCDDBBCCD 1 Bright A_WeaponOffset(random(-4.0,4.0), random(32.0,36.0),WOF_INTERPOLATE);
		NBFG DBBCCDDBB 1 Bright A_WeaponOffset(random(-8.0,8.0), random(32.0,40.0),WOF_INTERPOLATE);
		NBFG E 2 Bright
		{
			A_WeaponOffset(16.0, 48.0, WOF_INTERPOLATE);
			if (player == null)
			{
				return;
			}
			Weapon weap = player.ReadyWeapon;
			if (weap != null && invoker == weap && stateinfo != null && stateinfo.mStateType == STATE_Psprite)
			{
				if (!weap.DepleteAmmo (weap.bAltFire, true, deh.BFGCells))
					return;
			}
			SpawnPlayerMissile("DeathsheadBFGBall", angle, nofreeaim:sv_nobfgaim);
		}
		NBFG F 2 Bright A_WeaponOffset(8.0, 8.0, WOF_ADD|WOF_INTERPOLATE);
		NBFG G 2 Bright A_WeaponOffset(4.0, 4.0, WOF_ADD|WOF_INTERPOLATE);
		NBFG H 2 Bright A_WeaponOffset(-4.0, -4.0, WOF_ADD|WOF_INTERPOLATE);
		NBFG I 2 Bright A_WeaponOffset(-8.0, -8.0, WOF_ADD|WOF_INTERPOLATE);
		NBFG A 2 Bright A_WeaponOffset(-16.0, -16.0, WOF_ADD|WOF_INTERPOLATE);
		NBFG A 18;
		NBFG A 0 A_ReFire;
		Goto RealReady;
	}
}

class DeathsheadBFGBall : BFGBall
{
	Default
	{
		Damage 48;
		+FORCEXYBILLBOARD
		+BRIGHT
		+EXTREMEDEATH
	}
	States
	{
	Spawn:
		NBFB ABCD 2;
		Loop;
	Death:
		BFE1 A 8 Bright
		{
			A_Explode(128,128,0);
			A_Explode(64,256,0);
		}
		BFE1 B 8 Bright;
		BFE1 C 8 Bright A_BFGSpray;
		BFE1 DEF 8 Bright;
		Stop;
	}
}

class DeathsheadSG550Zoom : Inventory
{
	Default
	{
		Inventory.MaxAmount 1; 
	}
}
class DeathsheadSG550 : Pistol
{
	Default
	{
		Weapon.AmmoUse 2;
		Weapon.BobRangeX 1.25;
		Weapon.BobStyle "InverseSmooth";
		+WEAPON.NOALERT
		+INVENTORY.UNDROPPABLE
		Tag "$ACE_SG550";
	}
	States
	{
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Deselect:
		ADAS FGHIJK 2;
		TNT1 A 1 A_Lower(24);
		Wait;
	Ready:
		ADAS K 2 A_StartSound("weapons/sg550/deploy");
		ADAS JIHGFA 2;
	RealReady:
		ADAS A 1 A_WeaponReady;
		Wait;
	RealReadyZoomed:
		TNT1 A 1 A_WeaponReady;
		Wait;
	Fire:
		TNT1 A 0 A_JumpIfInventory("DeathsheadSG550Zoom",1,"FireZoomed");
		ADAS B 2 Bright
		{
			A_AlertMonsters();
			A_FireBullets (2, 3.5, -1, random(20,40), "BlueBastardBulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			A_StartSound("weapons/sg550", CHAN_AUTO);
			A_GunFlash();
			A_WeaponOffset(random(4.0,16.0), random(48.0,56.0),WOF_INTERPOLATE);
		}
		ADAS C 2 Bright;
		ADAS D 2;
		ADAS E 2 A_WeaponOffset(0.0, 32.0,WOF_INTERPOLATE);
		ADAS A 1;
		ADAS A 1 A_ReFire;
		Goto RealReady;
	FireZoomed:
		TNT1 A 0 Bright
		{
			A_AlertMonsters();
			A_FireBullets (0.5, 1, -1, random(20,40), "BlueBastardBulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			A_StartSound("weapons/sg550", CHAN_AUTO);
			A_SetPitch(self.pitch - 6, SPF_INTERPOLATE);
		}
		TNT1 AAA 2 Bright A_SetPitch(self.pitch + 2, SPF_INTERPOLATE);
		TNT1 AAA 1;
		TNT1 A 1 A_ReFire;
		Goto RealReadyZoomed;
	AltFire:
		ADAS N 0 A_StartSound("weapons/sg550/zoom", CHAN_AUTO);
		ADAS N 0 A_JumpIfInventory("DeathsheadSG550Zoom",1,"UnZoom");
		ADAS N 1;
		ADAS O 2;
		ADAS P 1;
		ADAS Q 2 A_ZoomFactor(1.25);
		ADAS R 1 A_ZoomFactor(1.5);
		ADAS S 2 A_ZoomFactor(1.75);
		ADAS S 0 {A_GiveInventory("DeathsheadSG550Zoom",1); A_ZoomFactor(2.0);}
		Goto AltHold;
	UnZoom:
		ADAS S 1 A_ZoomFactor(1.75);
		ADAS R 2 A_ZoomFactor(1.5);
		ADAS Q 1 A_ZoomFactor(1.25);
		ADAS P 2 A_ZoomFactor(1.0);
		ADAS O 1;
		ADAS N 2;
		ADAS A 1 A_TakeInventory("DeathsheadSG550Zoom",1);
		Goto AltHold;
	AltHold:
		TNT1 A 0 A_JumpIfInventory("DeathsheadSG550Zoom",1,3);
		ADAS A 1;
		TNT1 A 0 A_ReFire("AltHold");
		Goto RealReady;
		TNT1 A 1;
		TNT1 A 0 A_ReFire("AltHold");
		Goto RealReadyZoomed;
	Flash:
		ADAS L 2 Bright A_Light2;
		ADAS M 2 Bright A_Light1;
		Goto LightDone;
	}
}

class DeathsheadM4 : Chaingun
{
	Default
	{
		Weapon.AmmoType1 "Clip";
		Weapon.AmmoType2 "RocketAmmo";
		Weapon.AmmoUse1 1;
		Weapon.AmmoUse2 1;
		Weapon.BobRangeY 0.5;
		Weapon.BobStyle "InverseSmooth";
		Tag "$ACE_M4";
		+INVENTORY.UNDROPPABLE
	}
	States
	{
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Deselect:
		ADM4 FGHIJK 2;
		TNT1 A 1 A_Lower(24);
		Wait;
	Ready:
		ADM4 K 2 A_StartSound("weapons/autoshotgun/deploy");
		ADM4 JIHGFEA 2;
	RealReady:
		ADM4 A 1 A_WeaponReady;
		Loop;
	Fire:
		ADM4 B 1 Bright
		{
			A_FireBullets (4.5, 3, -1, random(8,18), "BlueBastardBulletPuff", FBF_USEAMMO|FBF_NORANDOM);
			A_StartSound("weapons/m4", CHAN_AUTO);
			A_WeaponOffset(random(-4.0,8.0), random(32.0,48.0),WOF_INTERPOLATE);
			A_GunFlash();
		}
		ADM4 C 2 Bright A_WeaponOffset(0.0, 32.0,WOF_INTERPOLATE);
		ADM4 DE 2 A_ReFire;
		Goto RealReady;
	AltFire:
		ADM4 B 2 A_FireProjectile("DeathsheadM4Grenade",0,true,0,0,0,-6);
		ADM4 CDEA 2;
		ADM4 A 14 A_WeaponReady(WRF_NOSECONDARY);
		Goto RealReady;
	Flash:
		ADM4 L 1 Bright A_Light1;
		ADM4 M 2 Bright A_Light2;
		Goto LightDone;
	Spawn:
		ADMC A -1;
		Stop;
	}
}

class DeathsheadM4Grenade : Grenade
{
	Default
	{
		BounceType "None";
		SeeSound "weapons/m4/grenade";
		DeathSound "weapons/rocklx";
	}
}

class DeathsheadLevelEnter : DoomWeapon
{
	Default
	{
		Tag " ";
		+INVENTORY.UNDROPPABLE
	}
	States
	{
	Select:
		TNT1 A 0 A_JumpIf(skip_intros == true, "Fire");
		TNT1 A 1 A_Raise(24);
		Wait;
	Deselect:
		TNT1 A 1 A_Lower(24);
		Wait;
	Ready:
		TNT1 A 0 A_Jump(256,"Ready1","Ready2","Ready3","Ready4","Ready5");
	Ready1:
		ADWD A 2 A_StartSound("misc/bottle_open", CHAN_AUTO);
		ADWD BCDEF 2;
		ADWD G 2 A_StartSound("misc/drink", CHAN_AUTO);
		ADWD H 2;
		ADWD F 3;
		ADWD G 2 A_StartSound("misc/drink", CHAN_AUTO);
		ADWD H 2;
		ADWD F 3;
		ADWD G 2 A_StartSound("misc/drink", CHAN_AUTO);
		ADWD H 2;
		ADWD F 3;
		ADWD I 2 A_StartSound("weapons/deagle/deploy", CHAN_AUTO);
		ADWD JKLMNOPQRSTUVW 2;
		TNT1 A 2;
		TNT1 A 2 A_StartSound("misc/glass_break", CHAN_AUTO);
		Goto Fire;
	Ready2:
		ADFS HG 2;
		ADFS E 2 A_StartSound("weapons/fists/deploy");
		ADFS FGHKLM 2;
		Goto Fire;
	Ready3:
		ADDR A 2 A_StartSound("misc/can_open", CHAN_AUTO);
		ADDR BCDEFG 2;
		ADDR H 2 A_StartSound("misc/drink", CHAN_AUTO);
		ADDR IJKLMNOPDCBA 2;
		Goto Fire;
	Ready4:
		ADMA ABCDEFGHIJKLMEDCBA 2;
		Goto Fire;
	Ready5:
		ADSM ABCDE 2;
		ADSM F 2 A_StartSound("misc/zippo/open");
		ADSM GHIJKL 2;
		ADSM M 2 A_StartSound("misc/zippo/close");
		ADSM NOPQRS 2;
		Goto Fire;
	Fire:
		TNT1 A 1 A_TakeInventory("DeathsheadLevelEnter");
		Wait;
	}
}