#include "./deathshead/intros.zsc"
#include "./deathshead/melee.zsc" //Includes fists, chainsaw and the kick.
#include "./deathshead/bullet.zsc" //Includes all weapons that use bullets.
#include "./deathshead/shells.zsc" //Includes all weapons that use shells.
#include "./deathshead/rockets.zsc"//etc
#include "./deathshead/cells.zsc"//etc


mixin class BBDeathsheadWeapon //the mixing classes are classes you add in to the class, which is great for more minor stuff.
{
	default
	{
		Inventory.RestrictedTo "Deathshead";
	}
}