class DeathsheadFist : Fist
{
	States
	{
	Ready:
		ADFS A 1 A_WeaponReady;
		Loop;
	Deselect:
		ADFS A 1 A_Lower(24);
		Loop;
	Select:
		ADFS A 1 A_Raise(24);
		Loop;
	Fire:
		ADFS C 2;
		ADFS D 2 A_Punch;
		ADFS D 2 A_WeaponOffset(2.0, 2.0, WOF_ADD);
		ADFS C 2 A_WeaponOffset(0.0, 32.0);
		ADFS CC 2 A_WeaponOffset(2.0, 4.0, WOF_ADD);
		ADFS B 2 A_WeaponOffset(0.0, 32.0);
		ADFS B 2 A_WeaponOffset(2.0, 4.0, WOF_ADD);
		ADFS B 2 A_ReFire;
		Goto Ready;
	}
}

class DeathsheadPistol : Pistol
{
	States
	{
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Deselect:
		ADPS GHIJK 2;
		TNT1 A 1 A_Lower(24);
		Wait;
	Ready:
		ADPS K 0 A_StartSound("weapons/adpistol/deploy");
		ADPS KJIHGDA 2;
	RealReady:
		ADPS A 1 A_WeaponReady;
		Wait;
	Fire:
		ADPS A 2 Bright
		{
			A_FireBullets (6, 2, 1, 6, "BulletPuff");
			A_StartSound("weapons/adpistol", CHAN_WEAPON);
			A_GunFlash();
		}
		ADPS BB 1 A_WeaponOffset(2.0, 2.0, WOF_ADD);
		ADPS CC 1 A_WeaponOffset(1.0, 3.0, WOF_ADD);
		ADPS D 2 A_WeaponOffset(0.0, 32.0);
		ADPS D 0 A_ReFire;
		Goto RealReady;
	Flash:
		ADPS E 2 Bright A_Light1;
		ADPS F 2 Bright A_Light1;
		Goto LightDone;
 	Spawn:
		ADPS A -1;
		Stop;
	}
}