class ChainsawReplacement : CustomInventory replaces Chainsaw
{
	Default
	{
		Inventory.PickupMessage "$GOTSLOT1";
		Inventory.PickupSound "misc/metalslug";
		Tag "$TAG_CHAINSAW";
	}
	States
	{
	Spawn:
		WPN1 A 8;
		WPN1 A 8 Bright;
		WPN1 AABC 2;
		WPN1 DEFG 2 Bright;
		WPN1 HIJA 2;
		WPN1 A 8 Bright;
		Loop;
	Pickup:
		TNT1 A 0
		{
			if (CheckInventory("SpotMallet", 1)) A_GiveInventory("SpotChainsaw", 1, false);
			if (CheckInventory("DeathsheadFist", 1)) A_GiveInventory("DeathsheadChainsaw", 1, false);
		}
		Stop;
	}
}

class PistolReplacement : CustomInventory replaces Pistol
{
	Default
	{
		Inventory.PickupMessage "$GOTSLOT2";
		Inventory.PickupSound "misc/metalslug";
		Tag "$TAG_PISTOL";
	}
	States
	{
	Spawn:
		WPN2 A 8;
		WPN2 A 8 Bright;
		WPN2 AABC 2;
		WPN2 DEFG 2 Bright;
		WPN2 HIJA 2;
		WPN2 A 8 Bright;
		Loop;
	Pickup:
		TNT1 A 0
		{
			if (CheckInventory("SpotMallet", 1)) A_GiveInventory("SpotExpress600", 1, false);
			if (CheckInventory("DeathsheadFist", 1)) A_GiveInventory("DeathsheadPistol", 1, false);
		}
		Stop;
	}
}

class ShotgunReplacement : CustomInventory replaces Shotgun
{
	Default
	{
		Inventory.PickupMessage "$GOTSLOT3";
		Inventory.PickupSound "misc/shotgun_pkup";
		Tag "$TAG_SHOTGUN";
	}
	States
	{
	Spawn:
		WPN3 A 8;
		WPN3 A 8 Bright;
		WPN3 AABC 2;
		WPN3 DEFG 2 Bright;
		WPN3 HIJA 2;
		WPN3 A 8 Bright;
		Loop;
	Pickup:
		TNT1 A 0
		{
			if (CheckInventory("SpotMallet", 1)) A_GiveInventory("SpotShotgun", 1, false);
			if (CheckInventory("DeathsheadFist", 1)) A_GiveInventory("DeathsheadShotgun", 1, false);
		}
		Stop;
	}
}

class SuperShotgunReplacement : CustomInventory replaces SuperShotgun
{
	Default
	{
		Inventory.PickupMessage "$GOTSLOT3PLUS";
		Inventory.PickupSound "misc/shotgun_pkup";
		Tag "$TAG_SUPERSHOTGUN";
	}
	States
	{
	Spawn:
		WPNS A 8;
		WPNS A 8 Bright;
		WPNS AABC 2;
		WPNS DEFG 2 Bright;
		WPNS HIJA 2;
		WPNS A 8 Bright;
		Loop;
	Pickup:
		TNT1 A 0
		{
			if (CheckInventory("SpotMallet", 1))
			{
				// welcome back int dice
				int roll_the_dice = random(0,1);
				switch (roll_the_dice) {
				case 0:
				  A_GiveInventory("SpotDevastator", 1, false);
				  break;
				case 1:
				  A_GiveInventory("SpotShotgunClassic", 1, false);
				  break;
				}
			}
			if (CheckInventory("DeathsheadFist", 1)) A_GiveInventory("DeathsheadSuperShotgun", 1, false);
		}
		Stop;
	}
}

class ChaingunReplacement : CustomInventory replaces Chaingun
{
	Default
	{
		Inventory.PickupMessage "$GOTSLOT4";
		Inventory.PickupSound "misc/hmg_pkup";
		Tag "$TAG_CHAINGUN";
	}
	States
	{
	Spawn:
		WPN4 A 8;
		WPN4 A 8 Bright;
		WPN4 AABC 2;
		WPN4 DEFG 2 Bright;
		WPN4 HIJA 2;
		WPN4 A 8 Bright;
		Loop;
	Pickup:
		TNT1 A 0
		{
			if (CheckInventory("SpotMallet", 1))
			{
				int roll_the_dice = random(0,1);
				switch (roll_the_dice) {
				case 0:
				  A_GiveInventory("SpotChaingun", 1, false);
				  break;
				case 1:
				  A_GiveInventory("SpotM249", 1, false);
				  break;
				}
			}
			if (CheckInventory("DeathsheadFist", 1))
			{
				int roll_the_dice = random(0,2);
				switch (roll_the_dice) {
				case 0:
				  A_GiveInventory("DeathsheadMAC10", 1, false);
				  break;
				case 1:
				  A_GiveInventory("DeathsheadM4", 1, false);
				  break;
				case 2:
				  A_GiveInventory("DeathsheadSG550", 1, false);
				  break;
				}
			}
		}
		Stop;
	}
}

class RocketLauncherReplacement : CustomInventory replaces RocketLauncher
{
	Default
	{
		Inventory.PickupMessage "$GOTSLOT5";
		Inventory.PickupSound "misc/rl_pkup";
		Tag "$TAG_ROCKETLAUNCHER";
	}
	States
	{
	Spawn:
		WPN5 A 8;
		WPN5 A 8 Bright;
		WPN5 AABC 2;
		WPN5 DEFG 2 Bright;
		WPN5 HIJA 2;
		WPN5 A 8 Bright;
		Loop;
	Pickup:
		TNT1 A 0
		{
			if (CheckInventory("SpotMallet", 1)) A_GiveInventory("SpotRocketLauncher", 1, false);
			if (CheckInventory("DeathsheadFist", 1)) A_GiveInventory("DeathsheadRocketLauncher", 1, false);
		}
		Stop;
	}
}

class PlasmaRifleReplacement : CustomInventory replaces PlasmaRifle
{
	Default
	{
		Inventory.PickupMessage "$GOTSLOT6";
		Inventory.PickupSound "misc/laser_pkup";
		Tag "$TAG_PLASMARIFLE";
	}
	States
	{
	Spawn:
		WPN6 A 8;
		WPN6 A 8 Bright;
		WPN6 AABC 2;
		WPN6 DEFG 2 Bright;
		WPN6 HIJA 2;
		WPN6 A 8 Bright;
		Loop;
	Pickup:
		TNT1 A 0
		{
			if (CheckInventory("SpotMallet", 1)) A_GiveInventory("SpotPlasmaRifle", 1, false);
			if (CheckInventory("DeathsheadFist", 1)) A_GiveInventory("DeathsheadPlasmaRifle", 1, false);
		}
		Stop;
  }
}

class BFG9000Replacement : CustomInventory replaces BFG9000
{
	Default
	{
		Inventory.PickupMessage "$GOTSLOT7";
		Inventory.PickupSound "misc/laser_pkup";
		Tag "$TAG_BFG9000";
	}
	States
	{
	Spawn:
		WPN7 A 8;
		WPN7 A 8 Bright;
		WPN7 AABC 2;
		WPN7 DEFG 2 Bright;
		WPN7 HIJA 2;
		WPN7 A 8 Bright;
		Loop;
	Pickup:
		TNT1 A 0
		{
			if (CheckInventory("SpotMallet", 1)) A_GiveInventory("SpotBFG", 1, false);
			if (CheckInventory("DeathsheadFist", 1)) A_GiveInventory("DeathsheadBFG", 1, false);
		}
		Stop;
  }
}

//Ammo specific stuff


class BBClip : BBAmmo replaces clip
{
	Default
	{
		Inventory.PickupMessage "$GOTCLIP";
		/*Inventory.Amount 10;
		Inventory.MaxAmount 200;
		Ammo.BackpackAmount 10;
		Ammo.BackpackMaxAmount 400;
		Inventory.Icon "CLIPA0";*/
		Tag "$AMMO_CLIP";
	}
	States
	{
	Spawn:
		CLIP A -1;
		Stop;
	Pickup:
		TNT1 A 0
		{

			if (CheckInventory("SpotMallet", 1)) 
			{
				A_GiveInventory("BBSpot600", A_ammomultiplier(2), false);
				A_GiveInventory("BBSpotNavalBullets", A_ammomultiplier(10), false);
				A_GiveInventory("Clip", A_ammomultiplier(10), false);
			}
			if (CheckInventory("DeathsheadFist", 1))
			{ 
				A_GiveInventory("BBDeathshead9mm", A_ammomultiplier(10), false);
				A_GiveInventory("BBDeathshead556", A_ammomultiplier(10), false);
			}
		}
		Stop;
	}
}
	

class BBClipBox : BBAmmo replaces clipbox
{
	Default
	{
		Inventory.PickupMessage "$GOTCLIPBOX";
		/*Inventory.Amount 10;
		Inventory.MaxAmount 200;
		Ammo.BackpackAmount 10;
		Ammo.BackpackMaxAmount 400;
		Inventory.Icon "CLIPA0";*/
		Tag "$AMMO_CLIP";
	}
	States
	{
	Spawn:
		AMMO A -1;
		Stop;
	Pickup:
		TNT1 A 0
		{

			if (CheckInventory("SpotMallet", 1)) 
			{
				A_GiveInventory("BBSpot600", A_ammomultiplier(10), false);
				A_GiveInventory("BBSpotNavalBullets", A_ammomultiplier(50), false);
				A_GiveInventory("Clip", A_ammomultiplier(50), false);
			}
			if (CheckInventory("DeathsheadFist", 1))
			{ 
				A_GiveInventory("BBDeathshead9mm", A_ammomultiplier(50), false);
				A_GiveInventory("BBDeathshead556", A_ammomultiplier(50), false);
			}
		}
		Stop;
	}
}

class BBShell : BBAmmo replaces Shell
{
	Default
	{
		Inventory.PickupMessage "$GOTSHELLS";
		/*Inventory.Amount 4;
		Inventory.MaxAmount 50;
		Ammo.BackpackAmount 4;
		Ammo.BackpackMaxAmount 100;
		Inventory.Icon "SHELA0";*/
		Tag "$AMMO_SHELLS";
	}
	States
	{
	Spawn:
		SHEL A -1;
		Stop;
	Pickup:
		TNT1 A 0
		{
			A_GiveInventory("Shell", A_ammomultiplier(4), false);
			if (CheckInventory("SpotMallet", 1)) 
			{
				A_GiveInventory("BBSpotDevastatorShell", A_ammomultiplier(4), false);
			}
			if (CheckInventory("DeathsheadFist", 1)){ }
		}
		Stop;
	}
}

class BBShellBox : BBAmmo replaces ShellBox
{
	Default
	{
		Inventory.PickupMessage "$GOTSHELLBOX";
	}
	States
	{
	Spawn:
		SBOX A -1;
		Stop;
	Pickup:
		TNT1 A 0
		{
			A_GiveInventory("Shell", A_ammomultiplier(20), false);
			if (CheckInventory("SpotMallet", 1)) 
			{
				A_GiveInventory("BBSpotDevastatorShell", A_ammomultiplier(10), false);
			}
			if (CheckInventory("DeathsheadFist", 1)){ }
		}
		Stop;
	}
}

class BBRocketAmmo : BBAmmo replaces RocketAmmo
{
	Default
	{
		Inventory.PickupMessage "$GOTROCKET";
		Tag "$AMMO_ROCKETS";
	}
	States
	{
	Spawn:
		ROCK A -1;
		Stop;
	Pickup:
		TNT1 A 0
		{
			A_GiveInventory("RocketAmmo", 1, false);
			if (CheckInventory("SpotMallet", 1)) {	}
			if (CheckInventory("DeathsheadFist", 1))
			{ 
				A_GiveInventory("BBDeathsheadGrenade", A_ammomultiplier(2), false);
			}
		}
		Stop;
	}
}
	

class BBRocketBox : BBAmmo replaces RocketBox
{
	Default
	{
		Inventory.PickupMessage "$GOTROCKBOX";
	}
	States
	{
	Spawn:
		BROK A -1;
		Stop;
	Pickup:
		TNT1 A 0
		{

			A_GiveInventory("RocketAmmo", A_ammomultiplier(5), false);
			if (CheckInventory("SpotMallet", 1)) {	}
			if (CheckInventory("DeathsheadFist", 1))
			{ 
				A_GiveInventory("BBDeathsheadGrenade", A_ammomultiplier(5), false);
			}
		}
		Stop;
	}
}

class BBCell : BBAmmo replaces Cell
{
	Default
	{
		Inventory.PickupMessage "$GOTCELL";
		Tag "$AMMO_CELLS";
	}
	States
	{
	Spawn:
		CELL A -1;
		Stop;
	Pickup:
		TNT1 A 0
		{
			A_GiveInventory("Cell", A_ammomultiplier(20), false);
			if (CheckInventory("SpotMallet", 1)) 
			{
				A_GiveInventory("BBSpotAtomicBomb", 1, false);
			}
			if (CheckInventory("DeathsheadFist", 1))
			{
				A_GiveInventory("BBDeathsheadBFGCell", 1, false);
			}
		}
		Stop;
	}
}

class BBCellPack : BBAmmo replaces CellPack
{
	Default
	{
		Inventory.PickupMessage "$GOTCELLBOX";
	}
	States
	{
	Spawn:
		CELP A -1;
		Stop;
	Pickup:
		TNT1 A 0
		{
			A_GiveInventory("Cell", A_ammomultiplier(100), false);
			if (CheckInventory("SpotMallet", 1)) 
			{
				A_GiveInventory("BBSpotAtomicBomb", 2, false);
			}
			if (CheckInventory("DeathsheadFist", 1))
			{
				A_GiveInventory("BBDeathsheadBFGCell", 2, false);
			}
		}
		Stop;
	}
}