class SpotMallet : Fist
{
	Default
	{
		+WEAPON.NOALERT
	}
	States
	{
	Ready:
		MALL A 1 A_WeaponReady;
		Loop;
	Deselect:
		MALL A 1 A_Lower;
		Loop;
	Select:
		MALL A 1 A_Raise;
		Loop;
	Fire:
		MALL BC 2 A_SetAngle(self.angle + 4);
		MALL C 2;
		Goto Hold_Check;
	Hold_Check:
		MALL C 0{
			if (player.cmd.buttons & BT_ATTACK)
			{
				return ResolveState("Hold");
			} 
			else
			{
				return ResolveState("Swing");
			}
		}
	Hold:
		MALL C 1;
		Goto Hold_Check;
	Swing:
		MALL DEF 1 A_SetAngle(self.angle - 4);
		MALL G 0 A_Recoil(-4);
		MALL G 0;
		MALL G 1{
			int dmg = random(15,50);
			A_SetAngle(self.angle - 4);
			if (FindInventory("PowerStrength"))
			{
				dmg *= 10;
			}
			A_CustomPunch(dmg, norandom:true, range: meleeRange + 20, meleesound: "weapons/mallet", misssound: "weapons/mallet/miss");
		}
		MALL HIJ 1 A_SetAngle(self.angle - 4);
		TNT1 A 10;
		MTCD DCBA 2;
		Goto Ready;
	}
}

class SpotChainsaw : Chainsaw
{
}

class DinkyBlasterAmmo : Ammo
{
    Default
    {
        Inventory.MaxAmount 10;
        Inventory.Amount 10;
        Inventory.Icon "CELL";
        Inventory.PickupMessage "Picked up... internals of a Dinky Blaster? WHAT?";
    }
}

class DinkyBlaster : Pistol
{
    Default
    {
        Weapon.AmmoGive 10;
        Weapon.AmmoUse 1;
        Weapon.AmmoType "DinkyBlasterAmmo";
        +WEAPON.AMMO_OPTIONAL
    }

	States
	{
	Ready:
		DNKB A 1 A_WeaponReady;
		Loop;
	Deselect:
		DNKB A 1 A_Lower;
		Loop;
	Select:
		DNKB A 1 A_Raise;
		Loop;
	Fire:
        DNKB A 0 A_JumpIfNoAmmo("Reload");
        DNKB A 0
        {   
            A_GunFlash();
            A_PlaySound("weapons/blaster/shoot");
        }
		DNKB C 3 A_FireBullets(1, 0, 0, 5, "DinkyPuff");
        DNKB B 4;
        DNKB A 4;
        DNKB A 0 A_ReFire;
        Goto Ready;
    Reload:
        DBSR A 0 A_PlaySound("weapons/blaster/reload");
        DBSR ABCDE 2;
        DBSR F 45{
            A_GiveInventory("DinkyBlasterAmmo", 10);
        }
        DBSR GHI 2;
        Goto Ready;
    Flash:
        DKFR A 3 Bright A_Light1;
        TNT1 A 1 A_Light0;
        stop;
    Spawn:
        BLST A -1;
        stop;
	}
}

class DinkyPuff : BulletPuff
{
    Default
    {
        RenderStyle "Add";
        Alpha 0.5;
        Scale 0.5;
        +NOBLOCKMAP;
        +NOGRAVITY;
    }
    States
    {
        Melee:
            Goto Spawn;
        Spawn:
            PLSE ABCDE 2 Bright;
            stop;
    }
}

class SpotShotgun : Shotgun
{
}

class SpotChaingun : Chaingun
{
}