class SpotMallet : Fist
{
	Default
	{
		+WEAPON.NOALERT
		+INVENTORY.UNDROPPABLE
		Weapon.BobStyle "InverseSmooth";
		Weapon.BobSpeed 1.75;
		Weapon.BobRangeX 1.2;
		Weapon.BobRangeY 0.6;
		Tag "$SPOT_MALLET";
		//Weapon.WeaponScaleX 0.75;
		//Weapon.WeaponScaleY 0.8;
	}
	States
	{
	Deselect:
		MTCD ABCDE 3;
		MTCD E 1 A_Lower(24);
		Wait;
	Select:
		MTCD E 1 A_Lower(24);
		Wait;
	Ready:
		MTCD EDC 3;
		MTCD A 0 A_PlaySound("weapons/generic/draw");
		MTCD BA 3;
	RealReady:
		MALL A 1 A_WeaponReady;
		Loop;
	Fire:
		MALL BCD 2 A_SetAngle(self.angle + 4, SPF_INTERPOLATE);
		MALL D 2;
		Goto Hold_Check;
	Hold_Check:
		MALL D 0{
			if (player.cmd.buttons & BT_ATTACK)
			{
				A_WeaponOffset(Random(-3,3),Random(-3,3) + 36);
				return ResolveState("Hold");
			} 
			else
			{
				return ResolveState("Swing");
			}
		}
	Hold:
		MALL D 1;
		Goto Hold_Check;
	Swing:
		MALL DEF 1 A_SetAngle(self.angle - 4, SPF_INTERPOLATE);
		MALL G 0 A_Recoil(-4);
		MALL G 0;
		MALL G 1{
			int dmg = random(15,50);
			A_SetAngle(self.angle - 4, SPF_INTERPOLATE);
			if (FindInventory("PowerStrength"))
			{
				dmg *= 10;
			}
			A_CustomPunch(dmg, norandom:true, range: meleeRange + 20, meleesound: "weapons/mallet", misssound: "weapons/mallet/miss");
		}
		MALL HIJ 1 A_SetAngle(self.angle - 4, SPF_INTERPOLATE);
		TNT1 A 10;
		MTCD EDCBA 3;
		Goto RealReady;
	}
}

class SpotExpress600 : Pistol
{
    Default
    {
        Weapon.AmmoUse 2;
        Weapon.AmmoType "Clip";
		Weapon.BobStyle "InverseSmooth";
		Weapon.BobSpeed 1.75;
		Weapon.BobRangeX 1.2;
		Weapon.BobRangeY 0.6;
		Tag "$SPOT_REV";
		
		+INVENTORY.UNDROPPABLE
    }

	States
	{
	Deselect:
		REVR ABCDE 2;
		TNT1 A 1 A_Lower(24);
		Wait;
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Ready:
		REVR EDC 2;
		REVR A 0 A_PlaySound("weapons/generic/draw");
		REVR BA 2;
	RealReady:
		BREV A 1 A_WeaponReady;
		Loop;
	Fire:
		BREV A 0 A_PlaySound("weapons/express600/prefire");
        BREV BBBBBBBBBB 1{
			A_WeaponOffset(Random(-3,3),Random(-3,3) + 36);
		}
        BREV A 2
        {   
            A_GunFlash();
			A_FireBullets(4,0,0,24, "BlueBastardBulletPuff");
            A_PlaySound("weapons/express600/fire", CHAN_WEAPON);
			A_SetPitch(self.pitch - 6, SPF_INTERPOLATE);
        }
		BREV C 0 A_Recoil(1);
		BREV CD 2 A_SetPitch(self.pitch + 2, SPF_INTERPOLATE);
		BREV E 2{
			A_SetPitch(self.pitch + 2, SPF_INTERPOLATE);
			A_ReFire();
		}
        Goto RealReady;
    Flash:
        REVF A 2 Bright A_Light1;
        TNT1 A 1 A_Light0;
        stop;
	}
}

class SpotShotgun : Shotgun
{
	Default{
		Weapon.AmmoType "Shell";
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 8;
		Weapon.BobStyle "InverseSmooth";
		Weapon.BobSpeed 1.75;
		Weapon.BobRangeX 1.2;
		Weapon.BobRangeY 0.6;
		Tag "$SPOT_KS23";

		+INVENTORY.UNDROPPABLE
	}
	States {
		Deselect:
			SSHR ABCDE 2;
			TNT1 A 1 A_Lower(24);
			Wait;
		Select:
			TNT1 A 1 A_Raise(24);
			Wait;
		Ready:
			TNT1 A 0 A_PlaySound("weapons/generic/draw");
			SSHR EDCBA 2;
			SSHT BCD 2;
			SSHT A 0 A_PlaySound("weapons/shotgun/pump");
			SSHT EF 2;
			SSHT EDCBA 2;
		RealReady:
			SSHT A 1 A_WeaponReady;
			Loop;
		Fire:
			SSTF A 0
			{
				A_FireBullets(7, 4, 25, 5, "BlueBastardBulletPuff");
				A_Recoil(1);
				A_PlaySound("weapons/ks23/fire", CHAN_WEAPON);
				A_GunFlash();
				A_SetPitch(self.pitch - 6, SPF_INTERPOLATE);
			}
			SSTF CBAA 1{
				A_SetPitch(self.pitch + 1, SPF_INTERPOLATE);
				A_WeaponOffset(Random(-2,2),Random(-2,2) + 36);
			}
			SSHT A 6;
			SSHT BCD 2;
			SSHT A 0 A_PlaySound("weapons/shotgun/pump");
			SSHT EF 2;
			SSHT EDCBA 2;
			SSHT A 0 A_ReFire;
			goto RealReady;
		Flash:
			SHTF A 1 Bright A_Light2;
			SHTF B 1 Bright A_Light1;
			TNT1 A 1 A_Light0;
			stop;
	}
}

class SpotShotgunClassic : SuperShotgun
{
	Default{
		Weapon.AmmoType "Shell";
		Weapon.AmmoUse 2;
		Weapon.AmmoGive 8;
		Weapon.BobStyle "InverseSmooth";
		Weapon.BobSpeed 1.75;
		Weapon.BobRangeX 1.2;
		Weapon.BobRangeY 0.6;
		Tag "$SPOT_SHTCLASSIC";

		+INVENTORY.UNDROPPABLE
	}
	States {
		Deselect:
			SH2R ABCDE 2;
			TNT1 A 1 A_Lower(24);
			Wait;
		Select:
			TNT1 A 1 A_Raise(24);
			Wait;
		Ready:
			TNT1 A 0 A_PlaySound("weapons/generic/draw");
			SH2R EDCBA 2;
			SH2C BCD 3;
			SSHT A 0 A_PlaySound("weapons/shotgun/pump");
			SH2C EF 3;
			SH2C EDCBA 2;
		RealReady:
			SHT2 A 1 A_WeaponReady;
			Loop;
		Fire:
			SHT2 A 0
			{
				A_FireBullets(12, 6, 32, 5, "BlueBastardBulletPuff");
				A_Recoil(4);
				A_PlaySound("weapons/ks23/fire", CHAN_WEAPON);
				A_GunFlash();
				A_SetPitch(self.pitch - 12, SPF_INTERPOLATE);
			}
			SHT2 BCAAAA 1{
				A_SetPitch(self.pitch + 2, SPF_INTERPOLATE);
				A_WeaponOffset(Random(-2,2),Random(-2,2) + 36);
			}
			SHT2 AAAAAA 2{
				A_WeaponOffset(Random(-1,1),Random(-1,1) + 36);
			}
			SH2C BCD 3;
			SH2C A 0 A_PlaySound("weapons/shotgun/pump");
			SH2C EF 3;
			SH2C EDCBA 3;
			SH2C A 0 A_ReFire;
			goto RealReady;
		Flash:
			SH2F A 1 Bright A_Light2;
			SH2F B 1 Bright A_Light1;
			TNT1 A 1 A_Light0;
			stop;
	}
}

class SpotDevastator : SuperShotgun
{
	Default{
		Weapon.AmmoType "Shell";
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 8;
		Weapon.BobStyle "InverseSmooth";
		Weapon.BobSpeed 1.75;
		Weapon.BobRangeX 1.2;
		Weapon.BobRangeY 0.6;
		Tag "$SPOT_DEV";

		+INVENTORY.UNDROPPABLE
	}
	States {
		Deselect:
			DVTR ABCDE 2;
			TNT1 A 1 A_Lower(24);
			Wait;
		Select:
			TNT1 A 1 A_Raise(24);
			Wait;
		Ready:
			DVTR EDC 2;
			DVTR A 0 A_PlaySound("weapons/autoshotgun/deploy");
			DVTR BA 2;
		RealReady:
			DVST A 1 A_WeaponReady;
			Loop;
		Fire:
			DVST B 0
			{
				A_FireBullets(7, 4, 16, 7, "BlueBastardBulletPuff");
				A_Recoil(1);
				A_PlaySound("weapons/shotgun/fire", CHAN_WEAPON);
				A_GunFlash();
				A_SetPitch(self.pitch - 4, SPF_INTERPOLATE);
			}
			DVST BC 1;
			DVST DE 2 A_SetPitch(self.pitch + 2, SPF_INTERPOLATE);
			DVST A 4;
			goto RealReady;
		Flash:
			DVTF A 1 Bright A_Light2;
			DVTF B 1 Bright A_Light1;
			TNT1 A 1 A_Light0;
			stop;
	}
}

class SpotChainsaw : Chainsaw
{
	Default
	{
		Weapon.BobStyle "InverseSmooth";
		Weapon.BobSpeed 1.75;
		Weapon.BobRangeX 1.2;
		Weapon.BobRangeY 0.6;
		Weapon.UpSound "";
		+WEAPON.MELEEWEAPON
		Tag "$SPOT_CHAINSAW";

		+INVENTORY.UNDROPPABLE
	}
	States
	{
		Deselect:
			SSWR ABCDE 2 A_StopSound(CHAN_6);
			TNT1 A 1 A_Lower(24);
			Wait;
		Select:
			TNT1 A 1 A_Raise(24);
			Wait;
		Ready:
			SSWR EDC 2;
			SSWP A 0 A_PlaySound("weapons/chainsaw/pull", CHAN_AUTO);
			SSWP ABC 2;
			SSWP DDEEFF 1 {
				A_WeaponOffset(Random(-2,2),Random(-2,2) + 36);
			}
			SSWP A 0 A_PlaySound("weapons/chainsaw/idle", CHAN_6, 1.0, true);
			SSWR BBAA 1 A_WeaponOffset(Random(-2,2),Random(-2,2) + 36);
		RealReady:
			SSAW AABBCCDD 1{
				A_WeaponReady();
				A_WeaponOffset(Random(-1,1),Random(-1,1) + 36);
			}
			Loop;
		Fire:
			SSWT A 1;
		RealFire:
			SSWP A 0 A_PlaySound("weapons/chainsaw/attack", CHAN_6, 1.0, true);
			SSWP A 0 A_Saw("","weapons/chainsaw",2,"BlueBastardBulletPuffSaw");
			SSWA AB 1 {
				A_WeaponOffset(Random(-3,3),Random(-3,3) + 36);
			}
			SSWA A 0 A_ReFire("RealFire");
			SSWT A 1;
			SSWP A 0 A_PlaySound("weapons/chainsaw/idle", CHAN_6, 1.0, true);
			Goto RealReady;
	}
}

class SpotRocketLauncher : RocketLauncher
{
		Default{
		Weapon.AmmoType "RocketAmmo";
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 4;
		Weapon.BobStyle "InverseSmooth";
		Weapon.BobSpeed 1.75;
		Weapon.BobRangeX 1.2;
		Weapon.BobRangeY 0.6;
		+WEAPON.NOAUTOFIRE
		+INVENTORY.UNDROPPABLE

		Tag "$SPOT_ROCKET";
	}
	States {
		Deselect:
			SMSR ABCDE 2;
			TNT1 A 1 A_Lower(24);
			Wait;
		Select:
			TNT1 A 1 A_Raise(24);
			Wait;
		Ready:
			SMSR EDC 2;
			SMSR A 0 A_PlaySound("weapons/missle/deploy");
			SMSR BA 2;
		RealReady:
			SMSL A 1 A_WeaponReady;
			Loop;
		Fire:
			SMSL A 0{
				A_FireProjectile("NapalmRocket", 1, true, -10, -10);
				A_FireProjectile("NapalmRocket", 1, true, -10, 10);
				A_FireProjectile("NapalmRocket", -1, true, 10, -10);
				A_FireProjectile("NapalmRocket", -1, true, 10, 10);
				A_Light(4);
				A_SetPitch(self.pitch - 6, SPF_INTERPOLATE);
			}
			SMSL BC 1{
				A_Light(2);
				A_WeaponOffset(Random(-2,2),Random(-2,2) + 36);
				A_SetPitch(self.pitch + 2, SPF_INTERPOLATE);
			}
			SMSL DDDDDDDDDDDD 1{
				A_Light0();
				A_WeaponOffset(Random(-4,4),Random(-4,4) + 36);
			}
			SMSL DDDDDDD 2{
				A_WeaponOffset(Random(-2,2),Random(-2,2) + 36);
			}
			SMSL A 0 A_Light0();
			SMSL DEF 2;
			SMSL A 0{;
				A_ReFire();
			}
			goto RealReady;
	}
}

// not as rapid anymore :(
class NapalmRocket : Rocket
{
	Default{
		Scale 1;
		Speed 24;
		Damage 16;
		SeeSound "weapons/nuke";
		DeathSound "weapons/nuke/explode";
	}

		States
	{
		Spawn:
			MISL A 1;
			Loop;
		Death:
			MISL B 0{
				A_QuakeEx( 3, 3, 3, 20, 0, 500 );
			} 
			// Napalm
			MISL BBBB 0{
				A_SpawnItemEx("NapalmFlame",0,0,0, random(-16,16),random(-16,16),0);
			}
			MISL B 8 Bright A_Explode;
			MISL C 6 Bright;
			MISL D 4 Bright;
			Stop;
	}
}

class NapalmFlame : Actor
{
	Default
	{
		Radius 16;
		Height 8;
		Scale 1.0;
		Speed 40;
		Damage 75;
		DeathSound "weapons/nuke/explode";
		+RANDOMIZE
		+ROCKETTRAIL
		+ZDOOMTRANS
	}

	States
	{
		Spawn:
			NFRL A 0;
		Death:
			NFRL ABCDEFGHIJKL 2 bright{
				RadiusAttack(target,15,32);
			}
			NFRD ABCDEFGHIJKLMNO 2 bright RadiusAttack(target,15,32);
			Stop;
	}
}

class SpotChaingun : Chaingun
{
	Default
	{
		Weapon.SelectionOrder 700;
		Weapon.AmmoUse 2;
		Weapon.AmmoGive 20;
		Weapon.AmmoType "Clip";
		Inventory.PickupMessage "$GOTCHAINGUN";
		Obituary "$OB_MPCHAINGUN";
		Tag "$TAG_CHAINGUN";

		Weapon.BobStyle "InverseSmooth";
		Weapon.BobSpeed 1.75;
		Weapon.BobRangeX 1.2;
		Weapon.BobRangeY 0.6;

		Tag "$SPOT_NAVAL";

		+INVENTORY.UNDROPPABLE
	}
	States
	{
	Deselect:
		SCGR ABCDE 2;
		TNT1 A 1 A_Lower(24);
		Wait;
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Ready:
		SCGR EDC 2;
		SCGR B 0 A_PlayWeaponSound("weapons/chaingun/deploy");
		SCGR BA 2;
	RealReady:
		SCHG A 1 A_WeaponReady;
		Loop;
	Fire:
		SCHG AAA 2{
			A_FireBullets(8.5,4.5,3,10,"BlueBastardBulletPuff");
			A_PlayWeaponSound("weapons/chaingun/fire");
			A_WeaponOffset(Random(-3,3),Random(-3,3) + 36);
			A_SetPitch(self.pitch - 3, SPF_INTERPOLATE);
			A_Recoil(2);
			A_GunFlash("Flash");
		}
		SCHG BBBBBBBBBCCCCCCDDD 1{
			A_WeaponOffset(Random(-2,2),Random(-2,2) + 36);
			A_SetPitch(self.pitch + 0.5, SPF_INTERPOLATE);
		}
		SCHG B 0 A_ReFire();
		Goto RealReady;
	Flash:
		SCGF A 1 Bright A_Light1;
		Goto LightDone;
	}
}


class SpotPlasmaRifle : PlasmaRifle
{
			Default{
		Weapon.AmmoType "Cell";
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 40;
		Weapon.BobStyle "InverseSmooth";
		Weapon.BobSpeed 1.75;
		Weapon.BobRangeX 1.2;
		Weapon.BobRangeY 0.6;
		+WEAPON.NOAUTOFIRE
		+INVENTORY.UNDROPPABLE

		Tag "$SPOT_LASER";
	}
	States {
		Deselect:
			LSRL ABCDE 2 A_StopSound(CHAN_6);
			TNT1 A 1 A_Lower(24);
			Wait;
		Select:
			TNT1 A 1 A_Raise(24);
			Wait;
		Ready:
			LSRL EDC 2;
			LSRL A 0 A_PlaySound("weapons/rocket/load");
			LSRL BA 2;
		RealReady:
			LASR A 1 A_WeaponReady;
			Loop;
		Fire:
			LASR A 0 A_PlaySound("weapons/laser/start", CHAN_6, 1, false);
			LASR B 2;
			LASR A 0 A_PlaySound("weapons/laser/fire", CHAN_6, 1, true);
		RealFire:
			LSRF ABC 1 Bright {
				int dmg = Random(5,25);
				A_RailAttack(dmg,0,true,"", "#8f8fff", RGF_SILENT|RGF_NORANDOMPUFFZ, 0, "BulletPuff", 0.5, 0.5, 0, 2, 0.5, 0);
				A_Light(Random(2,4));
				A_WeaponOffset(Random(-3,3),Random(-3,3) + 40);
			}
			LASR B 0 A_ReFire("RealFire");
			LASR A 0 A_StopSound(CHAN_6);
			LASR A 0 A_PlaySound("weapons/laser/stop", CHAN_6, 1, false);
			LASR BBBBBBBBBBBBBBB 1{
				A_Light0();
				A_WeaponOffset(Random(-1,1),Random(-1,1) + 40);
			}
			goto RealReady;
	}
}


class SpotBFG : BFG9000
{
		Default
	{
		Height 20;
		Weapon.SelectionOrder 2800;
		Weapon.AmmoUse 40;
		Weapon.AmmoGive 40;
		Weapon.AmmoType "Cell";
		+WEAPON.NOAUTOFIRE;
		+INVENTORY.UNDROPPABLE

		Weapon.BobSpeed 1.75;
		Weapon.BobRangeX 1.2;
		Weapon.BobRangeY 0.6;
		Weapon.BobStyle "InverseSmooth";

		Tag "$SPOT_MOFFOBLI";
	}
	States
	{
		Deselect:
			SFMR FEDCBA 3;
			TNT1 A 1 A_Lower(24);
			Wait;
		Select:
			TNT1 A 1 A_Raise(24);
			Wait;
		Ready:
			SFMR ABC 3;
			SFMR A 0 A_PlaySound("weapons/missle/deploy");
			SFMR DEF 3;
		RealReady:
			SFTM A 1 A_WeaponReady;
			Loop;
		Fire:
			SFTM A 0 A_PlaySound("weapons/nuke/alarm", CHAN_AUTO);
			SFTM AAAAAAAAAAAAAAA 1 {
				A_WeaponOffset(Random(-3,3),Random(-3,3) + 35);
			}
			SFTM AAAAAAA 1 {
				A_WeaponOffset(Random(-5,5),Random(-5,5) + 35);
			}
			SFTM BC 2;
			STMF D 0{
				A_QuakeEx(0.2,0.2,0.2, 15, 0, QF_RELATIVE, "");
				A_FireProjectile("SpotNuke");
				A_Recoil(4);
				A_SetPitch(self.pitch - 8);
				A_PlaySound("weapons/nuke", CHAN_AUTO);
			}
			SFTM DDDD 1 {
				A_WeaponOffset(Random(-3,3),Random(-3,3) + 35);
				A_SetPitch(self.pitch + 2, SPF_INTERPOLATE);
			}
			SFTM DDDDDDDDDDDD 1 {
				A_WeaponOffset(Random(-3,3),Random(-3,3) + 35);
			}
			SFTM D 3 A_CheckReload();
			SFTM EFG 3;
			TNT1 A 15;
			TNT1 A 0 A_PlaySound("weapons/nuke/load", CHAN_AUTO);
			TNT1 A 35;
			SFMR ABC 3;
			SFMR A 0 A_PlaySound("weapons/missle/deploy");
			SFMR DEF 3;
			SFMR F 3 A_ReFire();
			Goto RealReady;
	}
}

class SpotNuke : Actor
{
	Default
	{
		Radius 32;
		Height 32;
		Speed 40;
		Damage 150;
		Projectile;
		//DeathSound "weapons/nuke/explode";
		+DEHEXPLOSION
		+ROCKETTRAIL
		+ZDOOMTRANS
		+EXTREMEDEATH
	}

	States
	{
		Spawn:
			SNUK A 1;
			Loop;
		Death:
			MISL B 0{
				A_QuakeEx( 3, 3, 3, 90, 0, 3000 );
				RadiusAttack(target,400,300);
				A_PlaySound("weapons/nuke/explode", CHAN_AUTO, 1, false, 0.02);
			} 
			// OMFG
			MISL BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 0{
				A_SpawnItemEx("NukeFlame",0,0,0, random(-32,32),random(-32,32),0);
			}
			MISL B 8 Bright A_Explode;
			MISL BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 0{
				A_SpawnItemEx("NukeFlame",0,0,0, random(-48,48),random(-48,48),0);
			}
			MISL C 6 Bright A_Light(10);
			MISL BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 0{
				A_SpawnItemEx("NukeFlame",0,0,0, random(-64,64),random(-64,64),0);
			}
			MISL D 4 Bright A_Light(0);
			
			Stop;
	}
}

class NukeFlame : Actor
{
	Default
	{
		Radius 32;
		Height 16;
		Scale 2.0;
		Speed 40;
		Damage 150;
		DeathSound "weapons/nuke/explode";
		+RANDOMIZE
		+ROCKETTRAIL
		+ZDOOMTRANS
		+EXTREMEDEATH
	}

	States
	{
		Spawn:
			NFRL A 0;
		Death:
			NFRL ABCDEFGHIJKLABCDEFGHIJKL 2 bright{
				A_Fire();
				RadiusAttack(target,30,64);
			}
			NFRD ABCDEFGHIJKLMNO 2 bright RadiusAttack(target,30,64);
			Stop;
	}
}

class SpotLevelEnter : DoomWeapon
{
	Default
	{
		Tag " ";
		+INVENTORY.UNDROPPABLE
	}
	States
	{
	Select:
		TNT1 A 0 A_JumpIf(skip_intros == true, "Fire");
		TNT1 A 1 A_Raise(24);
		Wait;
	Deselect:
		TNT1 A 1 A_Lower(24);
		Wait;
	Ready:
		TNT1 A 0 A_Jump(256, "Ready1", "Ready2", "Ready3");
	Ready1:
		SPHN A 0 A_PlaySound("weapons/generic/draw");
		SPHN ABCD 4;
		SPHN E 60 A_PlaySound("misc/phone/sorry");
		// anyone who writes clean code will kill me.
		SPHN EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 1 {
			A_WeaponOffset(Random(-2,2),Random(-2,2)+15, WOF_INTERPOLATE);
		}
		SPHN FGH 4;
		SPHN A 0 A_PlaySound("weapons/mallet/miss");
		SPHN IJKLM 1;
		TNT1 A 0 A_PlaySound("misc/phone/break", CHAN_6);
		TNT1 A 0 A_QuakeEx(0.2,0.2,0.2, 35, 0, QF_RELATIVE, "");
		Goto Fire;
	Ready2:
		SVDK A 0 A_PlaySound("weapons/generic/draw");
		SVDK AB 2;
		SVDK A 0 A_PlaySound("misc/drink_alt");
		SVDK CD 2;
		SVDK EFGFEFGFE 3;
		SVDK DCBA 2;
		SPDB ABCDEDCBABCDEDCBA 2;
		Goto Fire;
	Ready3:
		SCRK ABCDE 2;
		SCRK F 2 A_PlaySound("weapons/fists/deploy");
		SCRK EDCBA 2;
		Goto Fire;
	Fire:
		TNT1 A 1 A_TakeInventory("SpotLevelEnter");
		Wait;
	}
}

class SpotKicky : CustomInventory
{
    States
    {
    Use:
		TNT1 A 0 {
			int kick_type = random(1,2);
			if (kick_type == 1){
				A_Overlay(-2,"Kicky",1);
			}
			else{
				A_Overlay(-2,"RoadHouse",1);
			}
		}
        TNT1 A 0 A_OverlayOffset(-2,0,16);
        Fail;
    Kicky:
        SKCK A 1 A_StartSound("weapons/kick/miss",CHAN_AUTO);
		SKCK BC 1;
        SKCK D 2 {
			int dmg = random(10,20);
			if (FindInventory("PowerStrength"))
			{
				dmg *= 6;
			}
			A_CustomPunch(dmg, norandom:true, pufftype: "BlueBastardKickPuff", range: meleeRange + 20, meleesound: "weapons/kick", misssound: "");
		}
        SKCK EFGHA 2;
        Stop;
	RoadHouse:
		SRDH A 1 A_StartSound("weapons/kick/miss",CHAN_AUTO);
		SRDH B 1;
        SRDH C 2 {
			int dmg = random(10,20);
			if (FindInventory("PowerStrength"))
			{
				dmg *= 6;
			}
			A_CustomPunch(dmg, norandom:true, pufftype: "BlueBastardKickPuff", range: meleeRange + 20, meleesound: "weapons/kick", misssound: "");
		}
        SRDH DEFGH 2;
        Stop;
    }
}