class SpotMallet : Fist
{
	Default
	{
		+WEAPON.NOALERT
		Weapon.BobStyle "InverseSmooth";
		Weapon.BobSpeed 1.75;
		Weapon.BobRangeX 1.2;
		Weapon.BobRangeY 0.6;
	}
	States
	{
	Ready:
		MALL A 1 A_WeaponReady;
		Loop;
	Deselect:
		MALL A 1 A_Lower;
		Loop;
	Select:
		MALL A 1 A_Raise;
		Loop;
	Fire:
		MALL BC 2 A_SetAngle(self.angle + 4);
		MALL C 2;
		Goto Hold_Check;
	Hold_Check:
		MALL C 0{
			if (player.cmd.buttons & BT_ATTACK)
			{
				return ResolveState("Hold");
			} 
			else
			{
				return ResolveState("Swing");
			}
		}
	Hold:
		MALL C 1;
		Goto Hold_Check;
	Swing:
		MALL DEF 1 A_SetAngle(self.angle - 4, SPF_INTERPOLATE);
		MALL G 0 A_Recoil(-4);
		MALL G 0;
		MALL G 1{
			int dmg = random(15,50);
			A_SetAngle(self.angle - 4, SPF_INTERPOLATE);
			if (FindInventory("PowerStrength"))
			{
				dmg *= 10;
			}
			A_CustomPunch(dmg, norandom:true, range: meleeRange + 20, meleesound: "weapons/mallet", misssound: "weapons/mallet/miss");
		}
		MALL HIJ 1 A_SetAngle(self.angle - 4, SPF_INTERPOLATE);
		TNT1 A 10;
		MTCD DCBA 2;
		Goto Ready;
	}
}

class SpotExpress600 : Pistol
{
    Default
    {
        Weapon.AmmoUse 2;
        Weapon.AmmoType "Clip";
		Weapon.BobStyle "InverseSmooth";
		Weapon.BobSpeed 1.75;
		Weapon.BobRangeX 1.2;
		Weapon.BobRangeY 0.6;
    }

	States
	{
	Deselect:
		REVR ABCDE 2;
		TNT1 A 1 A_Lower(24);
		Wait;
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Ready:
		REVR EDC 2;
		REVR A 0 A_PlaySound("weapons/generic/draw");
		REVR BA 2;
	RealReady:
		BREV A 1 A_WeaponReady;
		Loop;
	Fire:
		BREV A 0 A_PlaySound("weapons/express600/prefire");
        BREV BBBBBBBBBB 1{
			A_WeaponOffset(Random(-3,3),Random(-3,3) + 36);
		}
        BREV A 2
        {   
            A_GunFlash();
			A_FireBullets(4,0,0,24, "BlueBastardBulletPuff");
            A_PlaySound("weapons/express600/fire", CHAN_WEAPON);
			A_SetPitch(self.pitch - 6, SPF_INTERPOLATE);
        }
		BREV C 0 A_Recoil(1);
		BREV CDE 2 A_SetPitch(self.pitch + 2, SPF_INTERPOLATE);
        Goto RealReady;
    Flash:
        REVF A 2 Bright A_Light1;
        TNT1 A 1 A_Light0;
        stop;
	}
}

// Commenting for now, i'll think about readding it.
// class DinkyBlasterAmmo : Ammo
// {
//     Default
//     {
//         Inventory.MaxAmount 10;
//         Inventory.Amount 10;
//         //Inventory.Icon "";
//         Inventory.PickupMessage "Picked up... internals of a Dinky Blaster? WHAT?";
//     }
// }

// class DinkyBlaster : Pistol
// {
//     Default
//     {
//         Weapon.AmmoGive 10;
//         Weapon.AmmoUse 1;
//         Weapon.AmmoType "DinkyBlasterAmmo";
// 		Weapon.BobStyle "InverseSmooth";
// 		Weapon.BobSpeed 1.75;
// 		Weapon.BobRangeX 1.2;
// 		Weapon.BobRangeY 0.6;
//         +WEAPON.AMMO_OPTIONAL
//     }

// 	States
// 	{
// 	Ready:
// 		DNKB A 1 A_WeaponReady(WRF_ALLOWRELOAD);
// 		Loop;
// 	Deselect:
// 		DNKB A 1 A_Lower;
// 		Loop;
// 	Select:
// 		DNKB A 1 A_Raise;
// 		Loop;
// 	Fire:
//         DNKB A 0 A_JumpIfNoAmmo("Reload");
//         DNKB A 0
//         {   
//             A_GunFlash();
//             A_PlaySound("weapons/blaster/shoot");
//         }
// 		DNKB C 3 A_FireBullets(1, 0, 0, 7, "DinkyPuff");
//         DNKB B 3;
//         DNKB A 3;
//         DNKB A 0 A_ReFire;
//         Goto Ready;
//     Reload:
// 		DBSR A 0 A_JumpIfInventory("DinkyBlasterAmmo", 0, "Ready");
//         Goto RealReload;
// 	RealReload:
//         DBSR A 0 A_PlaySound("weapons/blaster/reload");
//         DBSR ABCDE 2;
//         DBSR F 45{
//             A_GiveInventory("DinkyBlasterAmmo", 10);
//         }
//         DBSR GHI 2;
// 		goto Ready;
//     Flash:
//         DKFR A 3 Bright A_Light1;
//         TNT1 A 1 A_Light0;
//         stop;
//     Spawn:
//         BLST A -1;
//         stop;
// 	}
// }

// class DinkyPuff : BulletPuff
// {
//     Default
//     {
//         RenderStyle "Add";
//         Alpha 0.5;
//         Scale 0.5;
//         +NOBLOCKMAP;
//         +NOGRAVITY;
//     }
//     States
//     {
//         Melee:
//             Goto Spawn;
//         Spawn:
//             PLSE ABCDE 2 Bright;
//             stop;
//     }
// }

class SpotShotgun : Shotgun
{
	Default{
		Weapon.AmmoType "Shell";
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 8;
		Weapon.BobStyle "InverseSmooth";
		Weapon.BobSpeed 1.75;
		Weapon.BobRangeX 1.2;
		Weapon.BobRangeY 0.6;
	}
	States {
		Deselect:
			SSHR ABCDE 2;
			TNT1 A 1 A_Lower(24);
			Wait;
		Select:
			TNT1 A 1 A_Raise(24);
			Wait;
		Ready:
			TNT1 A 0 A_PlaySound("weapons/generic/draw");
			SSHR EDCBA 2;
			SSHT BCD 2;
			SSHT A 0 A_PlaySound("weapons/shotgun/pump");
			SSHT EF 2;
			SSHT EDCBA 2;
		RealReady:
			SSHT A 1 A_WeaponReady;
			Loop;
		Fire:
			SSTF A 0
			{
				A_FireBullets(7, 4, 25, 5, "BlueBastardBulletPuff");
				A_Recoil(1);
				A_PlaySound("weapons/ks23/fire", CHAN_WEAPON);
				A_GunFlash();
				A_SetPitch(self.pitch - 6, SPF_INTERPOLATE);
			}
			SSTF CBAA 1{
				A_SetPitch(self.pitch + 1, SPF_INTERPOLATE);
				A_WeaponOffset(Random(-2,2),Random(-2,2) + 36);
			}
			SSHT A 6;
			SSHT BCD 2;
			SSHT A 0 A_PlaySound("weapons/shotgun/pump");
			SSHT EF 2;
			SSHT EDCBA 2;
			SSHT A 0 A_ReFire;
			goto RealReady;
		Flash:
			SHTF A 1 Bright A_Light2;
			SHTF B 1 Bright A_Light1;
			TNT1 A 1 A_Light0;
			stop;
		Spawn:
			BLST A -1;
			stop;
	}
}

class SpotDevastator : SuperShotgun
{
	Default{
		Weapon.AmmoType "Shell";
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 8;
		Weapon.BobStyle "InverseSmooth";
		Weapon.BobSpeed 1.75;
		Weapon.BobRangeX 1.2;
		Weapon.BobRangeY 0.6;
	}
	States {
		Deselect:
			DVTR ABCD 2;
			TNT1 A 1 A_Lower(24);
			Wait;
		Select:
			TNT1 A 1 A_Raise(24);
			Wait;
		Ready:
			DVTR DC 2;
			DVTR A 0 A_PlaySound("weapons/autoshotgun/deploy");
			DVTR BA 2;
		RealReady:
			DVST A 1 A_WeaponReady;
			Loop;
		Fire:
			DVST D 0
			{
				A_FireBullets(7, 4, 16, 7, "BlueBastardBulletPuff");
				A_Recoil(1);
				A_PlaySound("weapons/shotgun/fire", CHAN_WEAPON);
				A_GunFlash();
				A_SetPitch(self.pitch - 3, SPF_INTERPOLATE);
			}
			DVST DCB 2 A_SetPitch(self.pitch + 1, SPF_INTERPOLATE);
			DVST A 6;
			goto RealReady;
		Flash:
			DVTF B 2 Bright A_Light2;
			DVTF A 2 Bright A_Light1;
			TNT1 A 1 A_Light0;
			stop;
		Spawn:
			BLST A -1;
			stop;
	}
}

class SpotRustyClaws : Fist
{
	Default
	{
		Weapon.BobStyle "InverseSmooth";
		Weapon.BobSpeed 1.75;
		Weapon.BobRangeX 1.2;
		Weapon.BobRangeY 0.6;
		+WEAPON.MELEEWEAPON
	}
	States
	{
		Ready:
			CLWI A 1 A_WeaponReady;
			Loop;
		Deselect:
			CLWI A 1 A_Lower;
			Loop;
		Select:
			CLWI A 1 A_Raise;
			Loop;
		Fire:
			CLWI A 0 A_Jump(128,"FireLeft");
			CLWR AB 1;
			CLWR C 1 {
				int dmg = random(5,20);
				A_CustomPunch(dmg, norandom:true, pufftype:"BlueBastardBulletPuffStab", range: meleeRange + 20, meleesound: "weapons/claw/impact", misssound: "weapons/claw/swing");
			}
			CLWR DEF 1;
			Goto Ready;
		FireLeft:
			CLWL AB 1;
			CLWL C 1 {
				int dmg = random(5,20);
				A_CustomPunch(dmg, norandom:true, pufftype:"BlueBastardBulletPuffStab", range: meleeRange + 20, meleesound: "weapons/claw/impact", misssound: "weapons/claw/swing");
			}
			CLWL DEF 1;
			Goto Ready;
	}
}

class RapidMissileSpot : RocketLauncher
{
		Default{
		Weapon.AmmoType "RocketAmmo";
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 4;
		Weapon.BobStyle "InverseSmooth";
		Weapon.BobSpeed 1.75;
		Weapon.BobRangeX 1.2;
		Weapon.BobRangeY 0.6;
		+WEAPON.NOAUTOFIRE
	}
	States {
		Deselect:
			SMSR ABCD 2;
			TNT1 A 1 A_Lower(24);
			Wait;
		Select:
			TNT1 A 1 A_Raise(24);
			Wait;
		Ready:
			SMSR DC 2;
			SMSR A 0 A_PlaySound("weapons/missle/deploy");
			SMSR BA 2;
		RealReady:
			SMSL A 1 A_WeaponReady;
			Loop;
		Fire:
			SMSL A 0{
				A_FireProjectile("RapidLauncherMissle");
				A_Light1();
				A_SetPitch(self.pitch - 3, SPF_INTERPOLATE);
			}
			SMSL BCD 2 A_SetPitch(self.pitch + 1, SPF_INTERPOLATE);
			SMSL A 0{
				A_Light0();
				A_ReFire();
			}
			goto RealReady;
		Spawn:
			MINR Z -1;
			stop;
	}
}

class RapidLauncherMissle : Rocket
{
	Default{
		Scale 0.5;
		Speed 32;
		Damage 16;
		SeeSound "weapons/missle/fire";
	}
}

class SpotChaingun : Chaingun
{
	Default
	{
		Weapon.SelectionOrder 700;
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 20;
		Weapon.AmmoType "Clip";
		Inventory.PickupMessage "$GOTCHAINGUN";
		Obituary "$OB_MPCHAINGUN";
		Tag "$TAG_CHAINGUN";

		Weapon.BobStyle "InverseSmooth";
		Weapon.BobSpeed 1.75;
		Weapon.BobRangeX 1.2;
		Weapon.BobRangeY 0.6;
	}
	States
	{
	Deselect:
		SCGR A 0 A_StopSound(CHAN_6);
		SCGR ABCD 2;
		TNT1 A 1 A_Lower(24);
		Wait;
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Ready:
		SCGR DC 2;
		SCGR B 0 A_PlayWeaponSound("weapons/chaingun/deploy");
		SCGR BA 2;
	RealReady:
		SCHG A 1 A_WeaponReady;
		Loop;
	Fire:
		SCGR B 0 A_PlayWeaponSound("weapons/chaingun/spin_start");
		SCHG ABCD 3;
		SCHG ABCD 2;
		SCHG ABCD 1;
		SCHG A 0 A_PlaySound("weapons/chaingun/spin", CHAN_6, 1, true);
	RealFire:
		SCHG A 1{
			A_FireBullets(4.0,4.0,1,5,"BlueBastardBulletPuff");
			A_PlayWeaponSound("weapons/chaingun/fire");
			A_WeaponOffset(Random(-3,3),Random(-3,3) + 36);
			A_SetPitch(self.pitch - 2, SPF_INTERPOLATE);
			A_Recoil(0.25);

			int num = Random(1,2);
			if (num == 1){
				A_GunFlash("Flash1");
			}
			else {
				A_GunFlash("Flash2");
			}
		}
		SCHG C 1 A_SetPitch(self.pitch + 2, SPF_INTERPOLATE);
		CHGG B 0 A_ReFire("RealFire");
	RevDown:
		SCHG A 0 A_StopSound(CHAN_6);
		SCHG B 0 A_PlayWeaponSound("weapons/chaingun/spin_stop");
		SCHG ABCD 1;
		SCHG ABCD 2;
		SCHG ABCD 3;
		Goto RealReady;
	
	Flash1:
		SCGF A 1 Bright A_Light1;
		Goto LightDone;
	Flash2:
		SCGF B 1 Bright A_Light1;
		Goto LightDone;
	}
}

class SpotRocketLauncher : RocketLauncher
{
}

class SpotPlasmaRifle : PlasmaRifle
{
			Default{
		Weapon.AmmoType "Cell";
		Weapon.AmmoUse 1;
		Weapon.AmmoGive 40;
		Weapon.BobStyle "InverseSmooth";
		Weapon.BobSpeed 1.75;
		Weapon.BobRangeX 1.2;
		Weapon.BobRangeY 0.6;
		+WEAPON.NOAUTOFIRE
	}
	States {
		Deselect:
			LSRL ABCD 2 A_StopSound(CHAN_6);
			TNT1 A 1 A_Lower(24);
			Wait;
		Select:
			TNT1 A 1 A_Raise(24);
			Wait;
		Ready:
			LSRL DC 2;
			LSRL A 0 A_PlaySound("weapons/missle/deploy");
			LSRL BA 2;
		RealReady:
			LASR A 1 A_WeaponReady;
			Loop;
		Fire:
			LASR A 0 A_PlaySound("weapons/laser/fire", CHAN_6, 1, true);
			LASR B 1;
		RealFire:
			LASR CD 1 Bright {
				int dmg = Random(5,20);
				A_RailAttack(dmg,0,true,"", "#8f8fff", RGF_SILENT|RGF_NORANDOMPUFFZ, 0, "BulletPuff", 0.5, 0.5, 0, 2, 0.5, 0);
				A_Light1();
				A_WeaponOffset(Random(-3,3),Random(-3,3) + 40);
			}
			LASR B 0 A_ReFire("RealFire");
			LASR B 1{
				A_Light0();
			}
			LASR A 0 A_StopSound(CHAN_6);
			goto RealReady;
	}
}


class SpotBFG : BFG9000
{
		Default
	{
		Height 20;
		Weapon.SelectionOrder 2800;
		Weapon.AmmoUse 40;
		Weapon.AmmoGive 40;
		Weapon.AmmoType "Cell";
		+WEAPON.NOAUTOFIRE;

		Weapon.BobSpeed 1.75;
		Weapon.BobRangeX 1.2;
		Weapon.BobRangeY 0.6;
		Weapon.BobStyle "InverseSmooth";
	}
	States
	{
		Deselect:
			SFMR FEDCBA 3;
			TNT1 A 1 A_Lower(24);
			Wait;
		Select:
			TNT1 A 1 A_Raise(24);
			Wait;
		Ready:
			SFMR ABC 3;
			SFMR A 0 A_PlaySound("weapons/missle/deploy");
			SFMR DEF 3;
		RealReady:
			SFTM A 1 A_WeaponReady;
			Loop;
		Fire:
			SFTM A 0 A_PlaySound("weapons/nuke/alarm");
			SFTM AAAAAAAAAAAAAAA 1 {
				A_WeaponOffset(Random(-3,3),Random(-3,3) + 35);
			}
			SFTM AAAAAAA 1 {
				A_WeaponOffset(Random(-5,5),Random(-5,5) + 35);
			}
			SFTM BC 2;
			STMF D 0{
				A_QuakeEx(0.2,0.2,0.2, 15, 0, QF_RELATIVE, "");
				A_FireProjectile("SpotNuke");
				A_Recoil(4);
				A_SetPitch(self.pitch - 8);
				A_PlaySound("weapons/nuke");
			}
			SFTM DDDD 1 {
				A_WeaponOffset(Random(-3,3),Random(-3,3) + 35);
				A_SetPitch(self.pitch + 2, SPF_INTERPOLATE);
			}
			SFTM DDDDDDDDDDDD 1 {
				A_WeaponOffset(Random(-3,3),Random(-3,3) + 35);
			}

			SFTM EFG 3;
			TNT1 A 50;
			SFMR ABC 3;
			SFMR A 0 A_PlaySound("weapons/missle/deploy");
			SFMR DEF 3;
			Goto RealReady;
		Spawn:
			BFUG A -1;
			Stop;
	}
}

class SpotNuke : Actor
{
	Default
	{
		Radius 32;
		Height 32;
		Speed 40;
		Damage 150;
		Projectile;
		//DeathSound "weapons/nuke/explode";
		+DEHEXPLOSION
		+ROCKETTRAIL
		+ZDOOMTRANS
		+EXTREMEDEATH
	}

	States
	{
		Spawn:
			SNUK A 1;
			Loop;
		Death:
			MISL B 0{
				A_QuakeEx( 3, 3, 3, 90, 0, 3000 );
				RadiusAttack(target,400,300);
				A_PlaySound("weapons/nuke/explode", CHAN_AUTO, 1, false, 0.02);
			} 
			// OMFG
			MISL BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 0{
				A_SpawnItemEx("NukeFlame",0,0,0, random(-32,32),random(-32,32),0);
			}
			MISL B 8 Bright A_Explode;
			MISL BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 0{
				A_SpawnItemEx("NukeFlame",0,0,0, random(-48,48),random(-48,48),0);
			}
			MISL C 6 Bright A_Light(10);
			MISL BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 0{
				A_SpawnItemEx("NukeFlame",0,0,0, random(-64,64),random(-64,64),0);
			}
			MISL D 4 Bright A_Light(0);
			Stop;
	}
}

class NukeFlame : Actor
{
	Default
	{
		Radius 32;
		Height 16;
		Scale 2.0;
		Speed 40;
		Damage 150;
		DeathSound "weapons/nuke/explode";
		+RANDOMIZE
		+ROCKETTRAIL
		+ZDOOMTRANS
		+EXTREMEDEATH
	}

	States
	{
		Spawn:
			NFRL A 0;
		Death:
			NFRL ABCDEFGHIJKLABCDEFGHIJKL 2 bright{
				A_Fire();
				RadiusAttack(target,30,64);
			}
			NFRD ABCDEFGHIJKLMNO 2 bright A_Fire;
			Stop;
	}
}

class SpotLevelEnter : DoomWeapon
{
	States
	{
	Deselect:
		TNT1 A 1 A_Lower(24);
		Wait;
	Select:
		TNT1 A 1 A_Raise(24);
		Wait;
	Ready:
		TNT1 A 1 A_Jump(256, "Ready1", "Ready2", "Ready3");
	Ready1:
		SPHN A 0 A_PlaySound("weapons/generic/draw");
		SPHN ABCD 4;
		SPHN E 60 A_PlaySound("misc/phone/sorry");
		// anyone who writes clean code will kill me.
		SPHN EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 1 {
			A_WeaponOffset(Random(-2,2),Random(-2,2)+15, WOF_INTERPOLATE);
		}
		SPHN FGH 4;
		SPHN A 0 A_PlaySound("weapons/mallet/miss");
		SPHN IJKLM 1;
		TNT1 A 0 A_PlaySound("misc/phone/break", CHAN_6);
		TNT1 A 0 A_QuakeEx(0.2,0.2,0.2, 35, 0, QF_RELATIVE, "");
		TNT1 A 0 A_TakeInventory("SpotLevelEnter");
		Goto Fire;
	Ready2:
		SVDK A 0 A_PlaySound("weapons/generic/draw");
		SVDK AB 2;
		SVDK A 0 A_PlaySound("misc/drink_alt");
		SVDK CD 2;
		SVDK EFGFEFGFE 3;
		SVDK DCBA 2;
		SPDB ABCDEDCBABCDEDCBA 2;
		TNT1 A 0 A_TakeInventory("SpotLevelEnter");
		Goto Fire;
	Ready3:
		SCRK ABCDE 2;
		SCRK F 2 A_PlaySound("weapons/fists/deploy");
		SCRK EDCBA 2;
		TNT1 A 0 A_TakeInventory("SpotLevelEnter");
		Goto Fire;
	Fire:
		TNT1 A 1;
		Wait;
	}
}