class ChaingunReplacement : CustomInventory replaces Chaingun
{
	Default
	{
		Inventory.PickupMessage "$GOTCHAINGUN";
		Inventory.PickupSound "misc/w_pkup";
		Obituary "$OB_MPCHAINGUN";
		Tag "$TAG_CHAINGUN";
		+COUNTITEM
	}
	States
	{
	Spawn:
		MGUN A -1;
		Stop;
	Pickup:
		TNT1 A 0 A_GiveInventory("Clip",20);
		TNT1 A 0 A_JumpIfInventory("SpotMallet", 1, 2);
		TNT1 A 0 A_JumpIfInventory("DeathsheadFist", 1, 2);
		Stop;
		TNT1 A 0 A_GiveInventory("SpotChaingun");
		Stop;
		TNT1 A 0 A_GiveInventory("DeathsheadMAC10");
		Stop;
  }
}