class ChainsawReplacement : CustomInventory replaces Chainsaw
{
	Default
	{
		Inventory.PickupMessage "$GOTCHAINSAW";
		Inventory.PickupSound "misc/metalslug";
		Tag "$TAG_CHAINSAW";
	}
	States
	{
	Spawn:
		CSAW A -1;
		Stop;
	Pickup:
		TNT1 A 0 A_JumpIfInventory("SpotMallet", 1, 2);
		TNT1 A 0 A_JumpIfInventory("DeathsheadFist", 1, 2);
		Stop;
		TNT1 A 0 A_GiveInventory("SpotRustyClaws");
		Stop;
		TNT1 A 0 A_GiveInventory("DeathsheadChainsaw");
		Stop;
	}
}

class ShotgunReplacement : CustomInventory replaces Shotgun
{
	Default
	{
		Inventory.PickupMessage "$GOTSHOTGUN";
		Inventory.PickupSound "misc/shotgun_pkup";
		Tag "$TAG_SHOTGUN";
	}
	States
	{
	Spawn:
		SHOT A -1;
		Stop;
	Pickup:
		TNT1 A 0 A_JumpIfInventory("SpotMallet", 1, 2);
		TNT1 A 0 A_JumpIfInventory("DeathsheadFist", 1, 2);
		Stop;
		TNT1 A 0 A_GiveInventory("SpotShotgun");
		Stop;
		TNT1 A 0 A_GiveInventory("DeathsheadShotgun");
		Stop;
	}
}

class SuperShotgunReplacement : CustomInventory replaces SuperShotgun
{
	Default
	{
		Inventory.PickupMessage "$GOTSHOTGUN2";
		Inventory.PickupSound "misc/shotgun_pkup";
		Tag "$TAG_SUPERSHOTGUN";
	}
	States
	{
	Spawn:
		SGN2 A -1;
		Stop;
	Pickup:
		TNT1 A 0 A_JumpIfInventory("SpotMallet", 1, 2);
		TNT1 A 0 A_JumpIfInventory("DeathsheadFist", 1, 2);
		Stop;
		TNT1 A 0 A_GiveInventory("SpotDevastator");
		Stop;
		TNT1 A 0 A_GiveInventory("DeathsheadSuperShotgun");
		Stop;
	}
}

class ChaingunReplacement : CustomInventory replaces Chaingun
{
	Default
	{
		Inventory.PickupMessage "$GOTCHAINGUN";
		Inventory.PickupSound "misc/hmg_pkup";
		Tag "$TAG_CHAINGUN";
	}
	States
	{
	Spawn:
		MGUN A -1;
		Stop;
	Pickup:
		TNT1 A 0 A_JumpIfInventory("SpotMallet", 1, 2);
		TNT1 A 0 A_JumpIfInventory("DeathsheadFist", 1, 2);
		Stop;
		TNT1 A 0 A_GiveInventory("SpotChaingun");
		Stop;
		TNT1 A 0 A_GiveInventory("DeathsheadMAC10");
		Stop;
	}
}

class RocketLauncherReplacement : CustomInventory replaces RocketLauncher
{
	Default
	{
		Inventory.PickupMessage "$GOTLAUNCHER";
		Inventory.PickupSound "misc/rl_pkup";
		Tag "$TAG_ROCKETLAUNCHER";
	}
	States
	{
	Spawn:
		LAUN A -1;
		Stop;
	Pickup:
		TNT1 A 0 A_JumpIfInventory("SpotMallet", 1, 2);
		TNT1 A 0 A_JumpIfInventory("DeathsheadFist", 1, 2);
		Stop;
		TNT1 A 0 A_GiveInventory("RapidMissileSpot");
		Stop;
		TNT1 A 0 A_GiveInventory("DeathsheadRocketLauncher");
		Stop;
	}
}

class PlasmaRifleReplacement : CustomInventory replaces PlasmaRifle
{
	Default
	{
		Inventory.PickupMessage "$GOTPLASMA";
		Inventory.PickupSound "misc/laser_pkup";
		Tag "$TAG_PLASMARIFLE";
	}
	States
	{
	Spawn:
		PLAS A -1;
		Stop;
	Pickup:
		TNT1 A 0 A_JumpIfInventory("SpotMallet", 1, 2);
		TNT1 A 0 A_JumpIfInventory("DeathsheadFist", 1, 2);
		Stop;
		TNT1 A 0 A_GiveInventory("SpotPlasmaRifle");
		Stop;
		TNT1 A 0 A_GiveInventory("DeathsheadPlasmaRifle");
		Stop;
  }
}

class BFG9000Replacement : CustomInventory replaces BFG9000
{
	Default
	{
		Inventory.PickupMessage "$GOTBFG9000";
		Inventory.PickupSound "misc/laser_pkup";
		Tag "$TAG_BFG9000";
	}
	States
	{
	Spawn:
		BFUG A -1;
		Stop;
	Pickup:
		TNT1 A 0 A_JumpIfInventory("SpotMallet", 1, 2);
		TNT1 A 0 A_JumpIfInventory("DeathsheadFist", 1, 2);
		Stop;
		TNT1 A 0 A_GiveInventory("SpotBFG");
		Stop;
		TNT1 A 0 A_GiveInventory("DeathsheadBFG");
		Stop;
  }
}

class BlueBastardBulletPuff : BulletPuff
{
	Default
	{
		VSpeed 0;
		RenderStyle "Add";
		Alpha 0.8;
		+NOBLOCKMAP;
		+NOGRAVITY;
		+NOINTERACTION;
		+FORCEXYBILLBOARD;
		Scale 0.5;
	}
	States
	{
	Crash:
		TNT1 A 0 
		{
			scale = default.scale*random(1.0,1.5);
			A_StartSound("misc/ricochet",CHAN_AUTO,CHANF_DEFAULT,random(0,1)*random(0.5,1.0));
		}
		TNT1 A 0 A_Jump(192,"Puff1","Puff2");
		Stop;
	Puff1:
		FX57 ABCDEFGHIJ 2 Bright;
		Stop;
	Puff2:
		FX58 ABCDEFGHIJ 2 Bright;
		Stop;
	}
}

class BlueBastardBerserk : Berserk replaces Berserk
{
	Default
	{
		Inventory.PickupSound "misc/berserk";
	}
	States
	{
	Pickup:
		TNT1 A 0 A_GiveInventory("PowerStrength");
		TNT1 A 0 HealThing(100, 0);
		TNT1 A 0 A_JumpIfInventory("SpotMallet", 1, 2);
		TNT1 A 0 A_JumpIfInventory("DeathsheadFist", 1, 2);
		Stop;
		TNT1 A 0 A_SelectWeapon("SpotMallet");
		Stop;
		TNT1 A 0 A_SelectWeapon("DeathsheadFist");
		Stop;
	}
}
