class ChainsawReplacement : CustomInventory replaces Chainsaw
{
	Default
	{
		Inventory.PickupMessage "$GOTCHAINSAW";
		Inventory.PickupSound "misc/metalslug";
		Tag "$TAG_CHAINSAW";
	}
	States
	{
	Spawn:
		WPN1 A 8;
		WPN1 A 8 Bright;
		WPN1 AABC 2;
		WPN1 DEFG 2 Bright;
		WPN1 HIJA 2;
		WPN1 A 8 Bright;
		Loop;
	Pickup:
		TNT1 A 0 A_JumpIfInventory("SpotMallet", 1, 2);
		TNT1 A 0 A_JumpIfInventory("DeathsheadFist", 1, 2);
		Stop;
		TNT1 A 0 A_GiveInventory("SpotRustyClaws");
		Stop;
		TNT1 A 0 A_GiveInventory("DeathsheadChainsaw");
		Stop;
	}
}

class PistolReplacement : CustomInventory replaces Pistol
{
	Default
	{
		Inventory.PickupMessage "$PICKUP_PISTOL_DROPPED";
		Inventory.PickupSound "misc/metalslug";
		Tag "$TAG_PISTOL";
	}
	States
	{
	Spawn:
		WPN2 A 8;
		WPN2 A 8 Bright;
		WPN2 AABC 2;
		WPN2 DEFG 2 Bright;
		WPN2 HIJA 2;
		WPN2 A 8 Bright;
		Loop;
	Pickup:
		TNT1 A 0 A_JumpIfInventory("SpotMallet", 1, 2);
		TNT1 A 0 A_JumpIfInventory("DeathsheadFist", 1, 2);
		Stop;
		TNT1 A 0 A_GiveInventory("SpotExpress600");
		Stop;
		TNT1 A 0 A_GiveInventory("DeathsheadPistol");
		Stop;
	}
}

class ShotgunReplacement : CustomInventory replaces Shotgun
{
	Default
	{
		Inventory.PickupMessage "$GOTSHOTGUN";
		Inventory.PickupSound "misc/shotgun_pkup";
		Tag "$TAG_SHOTGUN";
	}
	States
	{
	Spawn:
		WPN3 A 8;
		WPN3 A 8 Bright;
		WPN3 AABC 2;
		WPN3 DEFG 2 Bright;
		WPN3 HIJA 2;
		WPN3 A 8 Bright;
		Loop;
	Pickup:
		TNT1 A 0 A_JumpIfInventory("SpotMallet", 1, 2);
		TNT1 A 0 A_JumpIfInventory("DeathsheadFist", 1, 2);
		Stop;
		TNT1 A 0 A_GiveInventory("SpotShotgun");
		Stop;
		TNT1 A 0 A_GiveInventory("DeathsheadShotgun");
		Stop;
	}
}

class SuperShotgunReplacement : CustomInventory replaces SuperShotgun
{
	Default
	{
		Inventory.PickupMessage "$GOTSHOTGUN2";
		Inventory.PickupSound "misc/shotgun_pkup";
		Tag "$TAG_SUPERSHOTGUN";
	}
	States
	{
	Spawn:
		WPNS A 8;
		WPNS A 8 Bright;
		WPNS AABC 2;
		WPNS DEFG 2 Bright;
		WPNS HIJA 2;
		WPNS A 8 Bright;
		Loop;
	Pickup:
		TNT1 A 0 A_JumpIfInventory("SpotMallet", 1, 2);
		TNT1 A 0 A_JumpIfInventory("DeathsheadFist", 1, 2);
		Stop;
		TNT1 A 0 A_GiveInventory("SpotDevastator");
		Stop;
		TNT1 A 0 A_GiveInventory("DeathsheadSuperShotgun");
		Stop;
	}
}

class ChaingunReplacement : CustomInventory replaces Chaingun
{
	Default
	{
		Inventory.PickupMessage "$GOTCHAINGUN";
		Inventory.PickupSound "misc/hmg_pkup";
		Tag "$TAG_CHAINGUN";
	}
	States
	{
	Spawn:
		WPN4 A 8;
		WPN4 A 8 Bright;
		WPN4 AABC 2;
		WPN4 DEFG 2 Bright;
		WPN4 HIJA 2;
		WPN4 A 8 Bright;
		Loop;
	Pickup:
		TNT1 A 0 A_JumpIfInventory("SpotMallet", 1, 2);
		TNT1 A 0 A_JumpIfInventory("DeathsheadFist", 1, 2);
		Stop;
		TNT1 A 0 A_GiveInventory("SpotChaingun");
		Stop;
		TNT1 A 0 A_GiveInventory("DeathsheadMAC10");
		Stop;
	}
}

class RocketLauncherReplacement : CustomInventory replaces RocketLauncher
{
	Default
	{
		Inventory.PickupMessage "$GOTLAUNCHER";
		Inventory.PickupSound "misc/rl_pkup";
		Tag "$TAG_ROCKETLAUNCHER";
	}
	States
	{
	Spawn:
		WPN5 A 8;
		WPN5 A 8 Bright;
		WPN5 AABC 2;
		WPN5 DEFG 2 Bright;
		WPN5 HIJA 2;
		WPN5 A 8 Bright;
		Loop;
	Pickup:
		TNT1 A 0 A_JumpIfInventory("SpotMallet", 1, 2);
		TNT1 A 0 A_JumpIfInventory("DeathsheadFist", 1, 2);
		Stop;
		TNT1 A 0 A_GiveInventory("RapidMissileSpot");
		Stop;
		TNT1 A 0 A_GiveInventory("DeathsheadRocketLauncher");
		Stop;
	}
}

class PlasmaRifleReplacement : CustomInventory replaces PlasmaRifle
{
	Default
	{
		Inventory.PickupMessage "$GOTPLASMA";
		Inventory.PickupSound "misc/laser_pkup";
		Tag "$TAG_PLASMARIFLE";
	}
	States
	{
	Spawn:
		WPN6 A 8;
		WPN6 A 8 Bright;
		WPN6 AABC 2;
		WPN6 DEFG 2 Bright;
		WPN6 HIJA 2;
		WPN6 A 8 Bright;
		Loop;
	Pickup:
		TNT1 A 0 A_JumpIfInventory("SpotMallet", 1, 2);
		TNT1 A 0 A_JumpIfInventory("DeathsheadFist", 1, 2);
		Stop;
		TNT1 A 0 A_GiveInventory("SpotPlasmaRifle");
		Stop;
		TNT1 A 0 A_GiveInventory("DeathsheadPlasmaRifle");
		Stop;
  }
}

class BFG9000Replacement : CustomInventory replaces BFG9000
{
	Default
	{
		Inventory.PickupMessage "$GOTBFG9000";
		Inventory.PickupSound "misc/laser_pkup";
		Tag "$TAG_BFG9000";
	}
	States
	{
	Spawn:
		WPN7 A 8;
		WPN7 A 8 Bright;
		WPN7 AABC 2;
		WPN7 DEFG 2 Bright;
		WPN7 HIJA 2;
		WPN7 A 8 Bright;
		Loop;
	Pickup:
		TNT1 A 0 A_JumpIfInventory("SpotMallet", 1, 2);
		TNT1 A 0 A_JumpIfInventory("DeathsheadFist", 1, 2);
		Stop;
		TNT1 A 0 A_GiveInventory("SpotBFG");
		Stop;
		TNT1 A 0 A_GiveInventory("DeathsheadBFG");
		Stop;
  }
}

class BlueBastardBulletPuff : BulletPuff
{
	Default
	{
		VSpeed 0;
		RenderStyle "Add";
		Alpha 0.8;
		+NOBLOCKMAP;
		+NOGRAVITY;
		+NOINTERACTION;
		+FORCEXYBILLBOARD;
		Scale 0.5;
	}
	States
	{
	Crash:
		TNT1 A 0 
		{
			scale = default.scale*random(1.0,1.5);
			A_StartSound("misc/ricochet",CHAN_AUTO,CHANF_DEFAULT,random(0,1)*random(0.5,1.0));
		}
		TNT1 A 0 A_Jump(192,"Puff1","Puff2");
		Stop;
	Puff1:
		FX57 ABCDEFGHIJ 2 Bright;
		Stop;
	Puff2:
		FX58 ABCDEFGHIJ 2 Bright;
		Stop;
	}
}

class BlueBastardBulletPuffSaw : BlueBastardBulletPuff
{
	Default
	{
		+EXTREMEDEATH
	}
}